<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class NotificationSettingsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $settings = [
            // SMS Settings
            [
                'key' => 'sms.batch_size',
                'value' => '50',
                'category' => 'sms',
                'type' => 'integer',
                'display_name' => 'SMS Batch Size',
                'description' => 'Number of SMS messages to process in each batch',
                'validation_rules' => 'required|integer|min:1|max:100',
                'is_editable' => true,
                'display_order' => 1,
            ],
            [
                'key' => 'sms.batch_delay',
                'value' => '1',
                'category' => 'sms',
                'type' => 'integer',
                'display_name' => 'Batch Delay (seconds)',
                'description' => 'Delay in seconds between processing batches',
                'validation_rules' => 'required|integer|min:0|max:60',
                'is_editable' => true,
                'display_order' => 2,
            ],
            [
                'key' => 'sms.pricing.basic',
                'value' => '0.35',
                'category' => 'sms',
                'type' => 'decimal',
                'display_name' => 'Basic Package Rate (BWP)',
                'description' => 'Cost per SMS unit for Basic package',
                'validation_rules' => 'required|numeric|min:0.01|max:10',
                'is_editable' => true,
                'display_order' => 3,
            ],
            [
                'key' => 'sms.pricing.standard',
                'value' => '0.30',
                'category' => 'sms',
                'type' => 'decimal',
                'display_name' => 'Standard Package Rate (BWP)',
                'description' => 'Cost per SMS unit for Standard package',
                'validation_rules' => 'required|numeric|min:0.01|max:10',
                'is_editable' => true,
                'display_order' => 4,
            ],
            [
                'key' => 'sms.pricing.premium',
                'value' => '0.25',
                'category' => 'sms',
                'type' => 'decimal',
                'display_name' => 'Premium Package Rate (BWP)',
                'description' => 'Cost per SMS unit for Premium package',
                'validation_rules' => 'required|numeric|min:0.01|max:10',
                'is_editable' => true,
                'display_order' => 5,
            ],
            [
                'key' => 'sms.characters_per_unit',
                'value' => '160',
                'category' => 'sms',
                'type' => 'integer',
                'display_name' => 'Characters per SMS Unit',
                'description' => 'Number of characters that constitute one SMS unit',
                'validation_rules' => 'required|integer|min:100|max:200',
                'is_editable' => true,
                'display_order' => 6,
            ],

            // Rate Limits
            [
                'key' => 'rate_limits.sms_daily',
                'value' => '1000',
                'category' => 'rate_limit',
                'type' => 'integer',
                'display_name' => 'SMS Daily Limit per User',
                'description' => 'Maximum SMS messages a user can send per day',
                'validation_rules' => 'required|integer|min:1|max:100000',
                'is_editable' => true,
                'display_order' => 1,
            ],
            [
                'key' => 'rate_limits.sms_hourly',
                'value' => '200',
                'category' => 'rate_limit',
                'type' => 'integer',
                'display_name' => 'SMS Hourly Limit per User',
                'description' => 'Maximum SMS messages a user can send per hour',
                'validation_rules' => 'required|integer|min:1|max:10000',
                'is_editable' => true,
                'display_order' => 2,
            ],
            [
                'key' => 'rate_limits.email_daily',
                'value' => '500',
                'category' => 'rate_limit',
                'type' => 'integer',
                'display_name' => 'Email Daily Limit per User',
                'description' => 'Maximum emails a user can send per day',
                'validation_rules' => 'required|integer|min:1|max:100000',
                'is_editable' => true,
                'display_order' => 3,
            ],
            [
                'key' => 'rate_limits.email_hourly',
                'value' => '100',
                'category' => 'rate_limit',
                'type' => 'integer',
                'display_name' => 'Email Hourly Limit per User',
                'description' => 'Maximum emails a user can send per hour',
                'validation_rules' => 'required|integer|min:1|max:10000',
                'is_editable' => true,
                'display_order' => 4,
            ],

            // Email Settings - SMTP Configuration
            [
                'key' => 'email.mailer',
                'value' => 'smtp',
                'category' => 'email',
                'type' => 'string',
                'display_name' => 'Mail Mailer',
                'description' => 'Mail driver to use (smtp, sendmail, etc)',
                'validation_rules' => 'required|string|in:smtp,sendmail,mailgun,ses',
                'is_editable' => true,
                'display_order' => 1,
            ],
            [
                'key' => 'email.host',
                'value' => '',
                'category' => 'email',
                'type' => 'string',
                'display_name' => 'Mail Host',
                'description' => 'SMTP server hostname',
                'validation_rules' => 'required|string|max:255',
                'is_editable' => true,
                'display_order' => 2,
            ],
            [
                'key' => 'email.port',
                'value' => '465',
                'category' => 'email',
                'type' => 'integer',
                'display_name' => 'Mail Port',
                'description' => 'SMTP server port',
                'validation_rules' => 'required|integer|min:1|max:65535',
                'is_editable' => true,
                'display_order' => 3,
            ],
            [
                'key' => 'email.username',
                'value' => '',
                'category' => 'email',
                'type' => 'string',
                'display_name' => 'Mail Username',
                'description' => 'SMTP authentication username',
                'validation_rules' => 'required|string|max:255',
                'is_editable' => true,
                'display_order' => 4,
            ],
            [
                'key' => 'email.password',
                'value' => '',
                'category' => 'email',
                'type' => 'password',
                'display_name' => 'Mail Password',
                'description' => 'SMTP authentication password',
                'validation_rules' => 'required|string|max:255',
                'is_editable' => true,
                'display_order' => 5,
            ],
            [
                'key' => 'email.encryption',
                'value' => 'ssl',
                'category' => 'email',
                'type' => 'string',
                'display_name' => 'Mail Encryption',
                'description' => 'Encryption protocol (ssl, tls, or none)',
                'validation_rules' => 'required|string|in:ssl,tls',
                'is_editable' => true,
                'display_order' => 6,
            ],
            [
                'key' => 'email.from_address',
                'value' => '',
                'category' => 'email',
                'type' => 'string',
                'display_name' => 'From Address',
                'description' => 'Default sender email address',
                'validation_rules' => 'required|email|max:255',
                'is_editable' => true,
                'display_order' => 7,
            ],
            [
                'key' => 'email.from_name',
                'value' => '',
                'category' => 'email',
                'type' => 'string',
                'display_name' => 'From Name',
                'description' => 'Default sender name',
                'validation_rules' => 'required|string|max:255',
                'is_editable' => true,
                'display_order' => 8,
            ],
            [
                'key' => 'email.max_attachment_size',
                'value' => '10', // In MB
                'category' => 'email',
                'type' => 'integer',
                'display_name' => 'Max Attachment Size (MB)',
                'description' => 'Maximum file size for email attachments in megabytes',
                'validation_rules' => 'required|integer|min:1|max:50',
                'is_editable' => true,
                'display_order' => 9,
            ],
            [
                'key' => 'email.cleanup_days',
                'value' => '30',
                'category' => 'email',
                'type' => 'integer',
                'display_name' => 'Attachment Cleanup Days',
                'description' => 'Number of days to keep email attachments before cleanup',
                'validation_rules' => 'required|integer|min:7|max:365',
                'is_editable' => true,
                'display_order' => 10,
            ],

            // Feature Flags
            [
                'key' => 'features.sms_enabled',
                'value' => '0',
                'category' => 'feature',
                'type' => 'boolean',
                'display_name' => 'Enable SMS Sending',
                'description' => 'Allow or block all SMS sending system-wide',
                'validation_rules' => 'required|boolean',
                'is_editable' => true,
                'display_order' => 1,
            ],
            [
                'key' => 'features.whatsapp_enabled',
                'value' => '0',
                'category' => 'feature',
                'type' => 'boolean',
                'display_name' => 'Enable WhatsApp Sending',
                'description' => 'Allow or block all WhatsApp sending system-wide',
                'validation_rules' => 'required|boolean',
                'is_editable' => true,
                'display_order' => 2,
            ],
            [
                'key' => 'features.email_enabled',
                'value' => '1',
                'category' => 'feature',
                'type' => 'boolean',
                'display_name' => 'Enable Email Sending',
                'description' => 'Allow or block all email sending system-wide',
                'validation_rules' => 'required|boolean',
                'is_editable' => true,
                'display_order' => 3,
            ],
            [
                'key' => 'features.allow_job_cancellation',
                'value' => '1',
                'category' => 'feature',
                'type' => 'boolean',
                'display_name' => 'Allow Job Cancellation',
                'description' => 'Allow users to cancel running bulk SMS/email jobs',
                'validation_rules' => 'required|boolean',
                'is_editable' => true,
                'display_order' => 4,
            ],
            [
                'key' => 'features.allow_attachments',
                'value' => '1',
                'category' => 'feature',
                'type' => 'boolean',
                'display_name' => 'Allow Email Attachments',
                'description' => 'Allow users to attach files to emails',
                'validation_rules' => 'required|boolean',
                'is_editable' => true,
                'display_order' => 5,
            ],
            [
                'key' => 'features.enable_webhooks',
                'value' => '0',
                'category' => 'feature',
                'type' => 'boolean',
                'display_name' => 'Enable Delivery Webhooks',
                'description' => 'Enable webhook callbacks for SMS/email delivery status',
                'validation_rules' => 'required|boolean',
                'is_editable' => true,
                'display_order' => 6,
            ],
            [
                'key' => 'features.staff_direct_messages_enabled',
                'value' => '1',
                'category' => 'feature',
                'type' => 'boolean',
                'display_name' => 'Enable Staff Direct Messaging',
                'description' => 'Allow or block internal staff direct messaging system-wide.',
                'validation_rules' => 'required|boolean',
                'is_editable' => true,
                'display_order' => 7,
            ],
            [
                'key' => 'features.staff_presence_launcher_enabled',
                'value' => '1',
                'category' => 'feature',
                'type' => 'boolean',
                'display_name' => 'Enable Online Staff Launcher',
                'description' => 'Show or hide the quiet online-staff launcher in the staff topbar.',
                'validation_rules' => 'required|boolean',
                'is_editable' => true,
                'display_order' => 8,
            ],

            // Internal Messaging Settings
            [
                'key' => 'internal_messaging.online_window_minutes',
                'value' => '2',
                'category' => 'internal_messaging',
                'type' => 'integer',
                'display_name' => 'Online Window (minutes)',
                'description' => 'How long a staff heartbeat remains valid before the user appears offline.',
                'validation_rules' => 'required|integer|min:1|max:60',
                'is_editable' => true,
                'display_order' => 1,
            ],
            [
                'key' => 'internal_messaging.launcher_poll_seconds',
                'value' => '45',
                'category' => 'internal_messaging',
                'type' => 'integer',
                'display_name' => 'Launcher Poll Interval (seconds)',
                'description' => 'How often the quiet launcher refreshes presence and unread counts.',
                'validation_rules' => 'required|integer|min:15|max:300',
                'is_editable' => true,
                'display_order' => 2,
            ],
            [
                'key' => 'internal_messaging.conversation_poll_seconds',
                'value' => '5',
                'category' => 'internal_messaging',
                'type' => 'integer',
                'display_name' => 'Conversation Poll Interval (seconds)',
                'description' => 'How often an open direct-message conversation checks for new messages.',
                'validation_rules' => 'required|integer|min:3|max:30',
                'is_editable' => true,
                'display_order' => 3,
            ],

            // WhatsApp Settings
            [
                'key' => 'whatsapp.account_sid',
                'value' => '',
                'category' => 'whatsapp',
                'type' => 'string',
                'display_name' => 'Twilio Account SID',
                'description' => 'Twilio account SID used for WhatsApp messaging',
                'validation_rules' => 'nullable|string|max:255',
                'is_editable' => true,
                'display_order' => 1,
            ],
            [
                'key' => 'whatsapp.auth_token',
                'value' => '',
                'category' => 'whatsapp',
                'type' => 'password',
                'display_name' => 'Twilio Auth Token',
                'description' => 'Twilio auth token used for WhatsApp API and webhook verification',
                'validation_rules' => 'nullable|string|max:255',
                'is_editable' => true,
                'display_order' => 2,
            ],
            [
                'key' => 'whatsapp.sender',
                'value' => '',
                'category' => 'whatsapp',
                'type' => 'string',
                'display_name' => 'WhatsApp Sender',
                'description' => 'Configured Twilio WhatsApp sender, for example whatsapp:+14155238886',
                'validation_rules' => 'nullable|string|max:255',
                'is_editable' => true,
                'display_order' => 3,
            ],
            [
                'key' => 'whatsapp.status_webhook_secret',
                'value' => '',
                'category' => 'whatsapp',
                'type' => 'password',
                'display_name' => 'Status Webhook Secret',
                'description' => 'Optional internal secret for WhatsApp status callbacks',
                'validation_rules' => 'nullable|string|max:255',
                'is_editable' => true,
                'display_order' => 4,
            ],
            [
                'key' => 'whatsapp.inbound_webhook_secret',
                'value' => '',
                'category' => 'whatsapp',
                'type' => 'password',
                'display_name' => 'Inbound Webhook Secret',
                'description' => 'Optional internal secret for inbound WhatsApp callbacks',
                'validation_rules' => 'nullable|string|max:255',
                'is_editable' => true,
                'display_order' => 5,
            ],
            [
                'key' => 'whatsapp.default_language',
                'value' => 'en',
                'category' => 'whatsapp',
                'type' => 'string',
                'display_name' => 'Default Template Language',
                'description' => 'Default language used when selecting WhatsApp templates',
                'validation_rules' => 'required|string|max:10',
                'is_editable' => true,
                'display_order' => 6,
            ],
            [
                'key' => 'whatsapp.sync_enabled',
                'value' => '1',
                'category' => 'whatsapp',
                'type' => 'boolean',
                'display_name' => 'Enable Template Sync',
                'description' => 'Allow scheduled and manual syncing of WhatsApp templates from Twilio',
                'validation_rules' => 'required|boolean',
                'is_editable' => true,
                'display_order' => 7,
            ],
            [
                'key' => 'whatsapp.template_sync_limit',
                'value' => '100',
                'category' => 'whatsapp',
                'type' => 'integer',
                'display_name' => 'Template Sync Limit',
                'description' => 'Maximum number of templates to request during a sync',
                'validation_rules' => 'required|integer|min:1|max:500',
                'is_editable' => true,
                'display_order' => 8,
            ],

            // Queue Settings (Advanced)
            [
                'key' => 'queue.job_timeout',
                'value' => '300',
                'category' => 'queue',
                'type' => 'integer',
                'display_name' => 'Job Timeout (seconds)',
                'description' => 'Maximum time a job can run before being terminated',
                'validation_rules' => 'required|integer|min:60|max:3600',
                'is_editable' => true,
                'display_order' => 1,
            ],
            [
                'key' => 'queue.job_retries',
                'value' => '3',
                'category' => 'queue',
                'type' => 'integer',
                'display_name' => 'Job Retry Attempts',
                'description' => 'Number of times to retry a failed job',
                'validation_rules' => 'required|integer|min:1|max:5',
                'is_editable' => true,
                'display_order' => 2,
            ],
            [
                'key' => 'queue.retry_delay',
                'value' => '60',
                'category' => 'queue',
                'type' => 'integer',
                'display_name' => 'Retry Delay (seconds)',
                'description' => 'Initial delay between retry attempts',
                'validation_rules' => 'required|integer|min:10|max:300',
                'is_editable' => true,
                'display_order' => 3,
            ],
        ];

        foreach ($settings as $setting) {
            DB::table('s_m_s_api_settings')->updateOrInsert(
                ['key' => $setting['key']],
                array_merge($setting, [
                    'created_at' => now(),
                    'updated_at' => now(),
                ])
            );
        }

        $this->command->info('Notification settings seeded successfully!');
        $this->command->info('Total settings: ' . count($settings));
    }
}
