<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;

return new class extends Migration {
    const TABLE_NAME = 'authors';
    const COL_FIRST_NAME = 'first_name';
    const COL_LAST_NAME = 'last_name';

    public function up(){
        Schema::create(self::TABLE_NAME, function (Blueprint $table) {
            $table->id();
            $table->string(self::COL_FIRST_NAME);
            $table->string(self::COL_LAST_NAME);
            $table->timestamps();

            $table->unique([self::COL_FIRST_NAME, self::COL_LAST_NAME]);
        });

        $authorsPrimary = [
            ['first_name' => 'J', 'last_name' => 'Farmer'],
            ['first_name' => 'L', 'last_name' => 'Jones'],
            ['first_name' => 'F', 'last_name' => 'Klein'],
            ['first_name' => 'C', 'last_name' => 'Moyo'],
            ['first_name' => 'S', 'last_name' => 'Ociti'],
            ['first_name' => 'B', 'last_name' => 'Mafusi'],
            ['first_name' => 'O', 'last_name' => 'Kame'],
            ['first_name' => 'L', 'last_name' => 'Lungisani'],
            ['first_name' => 'M', 'last_name' => 'Richards'],
            ['first_name' => 'R', 'last_name' => 'Setsiba'],
            ['first_name' => 'D', 'last_name' => 'Zulu'],
            ['first_name' => 'Daphne B', 'last_name' => 'Kgosidintsi'],
            ['first_name' => 'Ithuteng P', 'last_name' => 'Mokokwe'],
            ['first_name' => 'N.B.', 'last_name' => 'Mogatwane'],
            ['first_name' => 'K', 'last_name' => 'Ramodisa'],
            ['first_name' => 'M. E. P. H.', 'last_name' => 'Justin'],
            ['first_name' => 'O', 'last_name' => 'Tonoki'],
            ['first_name' => 'K', 'last_name' => 'Thupe'],
            ['first_name' => 'Gosaitse', 'last_name' => 'Kgathi'],
            ['first_name' => 'Marguerite', 'last_name' => 'Serema'],
            ['first_name' => 'Reofilwe Rio', 'last_name' => 'Seganabeng'],
            ['first_name' => 'M', 'last_name' => 'Sebele'],
            ['first_name' => 'Bontle', 'last_name' => 'Kuhlmann'],
            ['first_name' => 'Irene', 'last_name' => 'Bathobakae'],
            ['first_name' => 'Lydia', 'last_name' => 'Wangombe'],
            ['first_name' => 'Vivian', 'last_name' => 'Jenkins'],
            ['first_name' => 'Chrissie', 'last_name' => 'Lewis'],
            ['first_name' => 'V', 'last_name' => 'Francis'],
            ['first_name' => 'C', 'last_name' => 'Minkley'],
            ['first_name' => 'Rosinah T.', 'last_name' => 'Mokotedi'],
            ['first_name' => 'Jennifer', 'last_name' => 'Gardner'],
            ['first_name' => 'Ann', 'last_name' => 'Smith'],
            ['first_name' => 'O', 'last_name' => 'King'],
            ['first_name' => 'R', 'last_name' => 'Thapisa'],
            ['first_name' => 'T', 'last_name' => 'Thipe'],
            ['first_name' => 'S', 'last_name' => 'Tshweneyame'],
            ['first_name' => 'Dorcas', 'last_name' => 'Moatswi'],
            ['first_name' => 'A. A.', 'last_name' => 'Taiwo'],
            ['first_name' => 'T', 'last_name' => 'Ledikile'],
            ['first_name' => 'N', 'last_name' => 'Solomon'],
            ['first_name' => 'Christopher', 'last_name' => 'Tidimane'],
            ['first_name' => 'L', 'last_name' => 'Chipazi'],
            ['first_name' => 'O', 'last_name' => 'Makgonatsotlhe'],
            ['first_name' => 'M', 'last_name' => 'Mabote'],
            ['first_name' => 'T', 'last_name' => 'Keitumetse'],
            ['first_name' => 'I', 'last_name' => 'Kyeleve'],
            ['first_name' => 'D', 'last_name' => 'Letsholo'],
            ['first_name' => 'J', 'last_name' => 'Mogaladi'],
            ['first_name' => 'M', 'last_name' => 'Somolekae'],
            ['first_name' => 'B', 'last_name' => 'Bathshaakane'],
            ['first_name' => 'L', 'last_name' => 'Bogosing'],
            ['first_name' => 'R', 'last_name' => 'Malefho'],
            ['first_name' => 'M', 'last_name' => 'Mogomotsi'],
            ['first_name' => 'O', 'last_name' => 'Mosime'],
            ['first_name' => 'O', 'last_name' => 'Ramokwapa'],
            ['first_name' => 'J', 'last_name' => 'Egner'],
            ['first_name' => 'C', 'last_name' => 'Tshamekang'],
            ['first_name' => 'E', 'last_name' => 'Seeco'],
            ['first_name' => 'V', 'last_name' => 'Ngongola'],
            ['first_name' => 'O', 'last_name' => 'Maruatona'],
            ['first_name' => 'Patricia', 'last_name' => 'Baker'],
            ['first_name' => 'Fathima', 'last_name' => 'Dada'],
            ['first_name' => 'David', 'last_name' => 'Langhan'],
            ['first_name' => 'Heather', 'last_name' => 'Moore'],
            ['first_name' => 'Dudu', 'last_name' => 'Mogobjwa'],
            ['first_name' => 'Marion', 'last_name' => 'Drew'],
            ['first_name' => 'O', 'last_name' => 'Kolanyane'],
            ['first_name' => 'T', 'last_name' => 'Kgokgothwane'],
            ['first_name' => 'J', 'last_name' => 'Chengeta'],
            ['first_name' => 'A', 'last_name' => 'Mooiman'],
            ['first_name' => 'C', 'last_name' => 'Phuthego'],
            ['first_name' => 'L.E.', 'last_name' => 'Setabo'],
            ['first_name' => 'Janice', 'last_name' => 'Barrett'],
            ['first_name' => 'Katrien', 'last_name' => 'du Preez'],
            ['first_name' => 'Linelle', 'last_name' => 'Campbell'],
            ['first_name' => 'Lynette', 'last_name' => 'Chambers'],
            ['first_name' => 'Montsamaisa', 'last_name' => 'Kwati'],
            ['first_name' => 'Karen', 'last_name' => 'Maberly'],
            ['first_name' => 'K.M.', 'last_name' => 'Kebiditwe'],
            ['first_name' => 'C', 'last_name' => 'Fitzpatrick'],
            ['first_name' => 'O. K.', 'last_name' => 'Mabona'],
            ['first_name' => 'P', 'last_name' => 'Miti'],
            ['first_name' => 'P. K.', 'last_name' => 'Pitso'],
            ['first_name' => 'E. D.', 'last_name' => 'Chazeri'],
            ['first_name' => 'B', 'last_name' => 'Nchabe'],
            ['first_name' => 'E', 'last_name' => 'Mpenya'],
            ['first_name' => 'A', 'last_name' => 'Makhwa'],
            ['first_name' => 'C', 'last_name' => 'Ntshabele'],
            ['first_name' => 'G', 'last_name' => 'Setlalekgosi-Khan'],
            ['first_name' => 'N', 'last_name' => 'Rotsomo'],
            ['first_name' => 'G.K.', 'last_name' => 'Tamajobe'],
            ['first_name' => 'B', 'last_name' => 'Makosha'],
            ['first_name' => 'Emang', 'last_name' => 'Butale'],
            ['first_name' => 'Mpho', 'last_name' => 'Mmopi'],
            ['first_name' => 'Dimakatso', 'last_name' => 'Mahlanza'],
            ['first_name' => 'M', 'last_name' => 'Johnson'],
            ['first_name' => 'Mae', 'last_name' => 'Johnson'],
            ['first_name' => 'Gorata', 'last_name' => 'Gabanamotse'],
            ['first_name' => 'Tshabang', 'last_name' => 'Tlalanyane'],
            ['first_name' => 'M', 'last_name' => 'Modise'],
            ['first_name' => 'S', 'last_name' => 'Monageng'],
            ['first_name' => 'M', 'last_name' => 'Tlhankane'],
            ['first_name' => 'G', 'last_name' => 'Saurombe'],
            ['first_name' => 'B', 'last_name' => 'Tsholofelo'],
            ['first_name' => 'L', 'last_name' => 'Mafela'],
            ['first_name' => 'Rebecca', 'last_name' => 'Lekoko'],
            ['first_name' => 'R', 'last_name' => 'Solomon'],
            ['first_name' => 'K', 'last_name' => 'Kebaetse'],
            ['first_name' => 'G', 'last_name' => 'Keseitse'],
            ['first_name' => 'D', 'last_name' => 'Masogo'],
            ['first_name' => 'O', 'last_name' => 'Sibanda'],
            ['first_name' => 'Aviva', 'last_name' => 'Spector'],
            ['first_name' => 'Rosemary', 'last_name' => 'Golding'],
            ['first_name' => 'Gillian', 'last_name' => 'Leggat'],
            ['first_name' => 'Jenny', 'last_name' => 'Seed'],
            ['first_name' => 'Elizabeth', 'last_name' => 'Eagar'],
            ['first_name' => 'Rowland', 'last_name' => 'Warambwa'],
            ['first_name' => 'Colleen', 'last_name' => 'Dawson'],
            ['first_name' => 'L', 'last_name' => 'Mudongo'],
            ['first_name' => 'Pat', 'last_name' => 'Olifant'],
            ['first_name' => 'T', 'last_name' => 'Wamundila'],
            ['first_name' => 'M', 'last_name' => 'Jeina'],
            ['first_name' => 'G', 'last_name' => 'Thipe'],
            ['first_name' => 'K', 'last_name' => 'Gathimbu'],
            ['first_name' => 'I', 'last_name' => 'Magetse'],
            ['first_name' => 'H', 'last_name' => 'Mokgolodi'],
            ['first_name' => 'J', 'last_name' => 'Muchado'],
            ['first_name' => 'A', 'last_name' => 'Ongadile'],
            ['first_name' => 'Nancy', 'last_name' => 'Mutshewa'],
            ['first_name' => 'Paul', 'last_name' => 'Chakalisa'],
            ['first_name' => 'Oduetse', 'last_name' => 'Setlhare'],
            ['first_name' => 'Dorcas', 'last_name' => 'Morake'],
            ['first_name' => 'Martha', 'last_name' => 'Lempadi'],
            ['first_name' => 'Ruth', 'last_name' => 'Mokobi'],
            ['first_name' => 'Mmapula', 'last_name' => 'Morakaladi'],
            ['first_name' => 'Gobotsamang', 'last_name' => 'Leshetla'],
            ['first_name' => 'Segametsi C', 'last_name' => 'Setshwane'],
            ['first_name' => 'A', 'last_name' => 'Pitso'],
            ['first_name' => 'Tshekoetsile', 'last_name' => 'Kebabope'],
            ['first_name' => 'L.D', 'last_name' => 'Kganela'],
            ['first_name' => 'N.S', 'last_name' => 'Mokgachane'],
            ['first_name' => 'C', 'last_name' => 'Dingi'],
            ['first_name' => 'E', 'last_name' => 'Morei'],
            ['first_name' => 'C', 'last_name' => 'Moabankwe'],
            ['first_name' => 'Clyde', 'last_name' => 'Sibanda'],
            ['first_name' => 'Gervase', 'last_name' => 'Mujuni'],
            ['first_name' => 'Galeage', 'last_name' => 'Mogorosi'],
            ['first_name' => 'J.J.', 'last_name' => 'Kedikilwe'],
            ['first_name' => 'C', 'last_name' => 'Matlhare'],
            ['first_name' => 'P', 'last_name' => 'Maduku'],
            ['first_name' => 'Geoffrey', 'last_name' => 'Moswetsi'],
            ['first_name' => 'Kabelo', 'last_name' => 'Sentsho'],
            ['first_name' => 'M', 'last_name' => 'Mahloane'],
            ['first_name' => 'S', 'last_name' => 'Ngwako'],
            ['first_name' => 'Angela', 'last_name' => 'Cunningham'],
            ['first_name' => 'Dorcas', 'last_name' => 'Phiri'],
            ['first_name' => 'Olga', 'last_name' => 'Tsimanyana'],
            ['first_name' => 'H', 'last_name' => 'Mathole'],
            ['first_name' => 'P', 'last_name' => 'Molefe'],
            ['first_name' => 'Margot', 'last_name' => 'Long'],
            ['first_name' => 'D', 'last_name' => 'Bhusumane'],
            ['first_name' => 'Miriam Banana', 'last_name' => 'Maroba'],
            ['first_name' => 'Otsile Tiny', 'last_name' => 'Sento-Pelaelo'],
            ['first_name' => 'Mabona', 'last_name' => 'Mabona'],
            ['first_name' => 'Norman', 'last_name' => 'Rhudhumbu'],
            ['first_name' => 'Maria', 'last_name' => 'Dikeme'],
            ['first_name' => 'Dineo', 'last_name' => 'Timile'],
            ['first_name' => 'Goememang', 'last_name' => 'Mogapi'],
            ['first_name' => 'J', 'last_name' => 'Vermeulen'],
            ['first_name' => 'Herod', 'last_name' => 'Hlomani'],
            ['first_name' => 'Monamodi', 'last_name' => 'Kesamang'],
            ['first_name' => 'Mothooteng', 'last_name' => 'Lesang'],
            ['first_name' => 'E', 'last_name' => 'Kasolo'],
            ['first_name' => 'B', 'last_name' => 'Sefakana'],
            ['first_name' => 'P', 'last_name' => 'Dow'],
            ['first_name' => 'G', 'last_name' => 'Ramorogo'],
            ['first_name' => 'T', 'last_name' => 'Sengalo'],
            ['first_name' => 'Alice Boitumelo', 'last_name' => 'Potongwane'],
            ['first_name' => 'Ntebogang Gloria', 'last_name' => 'Dintle'],
            ['first_name' => 'B. E.', 'last_name' => 'Ketlhaotswe'],
            ['first_name' => 'L', 'last_name' => 'Motlaleng'],
            ['first_name' => 'T', 'last_name' => 'Malokana'],
            ['first_name' => 'N. T.', 'last_name' => 'Gababine'],
            ['first_name' => 'L', 'last_name' => 'Polelo'],
            
        ];

        $authorsJunior = [
            ['first_name' => 'V', 'last_name' => 'Ngongola'],
            ['first_name' => 'G', 'last_name' => 'Gatsha'],
            ['first_name' => 'K', 'last_name' => 'Selwe'],
            ['first_name' => 'S', 'last_name' => 'Sehuhula'],
            ['first_name' => 'Otsweletse', 'last_name' => 'Thuso'],
            ['first_name' => 'Philip', 'last_name' => 'Maduku'],
            ['first_name' => 'L', 'last_name' => 'Kasale'],
            ['first_name' => 'R', 'last_name' => 'Warambwa'],
            ['first_name' => 'A', 'last_name' => 'Hlabano'],
            ['first_name' => 'D', 'last_name' => 'Paizee'],
            ['first_name' => 'D', 'last_name' => 'Clohessy'],
            ['first_name' => 'N', 'last_name' => 'Thutoetsile'],
            ['first_name' => 'Isoka', 'last_name' => 'Omulepu'],
            ['first_name' => 'C', 'last_name' => 'Tidimane'],
            ['first_name' => 'J.B.', 'last_name' => 'Sengate'],
            ['first_name' => 'K', 'last_name' => 'Morrison'],
            ['first_name' => 'K', 'last_name' => 'Phadi'],
            ['first_name' => 'Karen', 'last_name' => 'Going'],
            ['first_name' => 'M', 'last_name' => 'Matanire'],
            ['first_name' => 'K', 'last_name' => 'Mojaphoko'],
            ['first_name' => 'W', 'last_name' => 'Sibanda'],
            ['first_name' => 'J', 'last_name' => 'Mokibelo'],
            ['first_name' => 'G', 'last_name' => 'Mmusi'],
            ['first_name' => 'C', 'last_name' => 'van Duyn'],
            ['first_name' => 'Jennifer', 'last_name' => 'Davis'],
            ['first_name' => 'R', 'last_name' => 'Moolman'],
            ['first_name' => 'P.M.', 'last_name' => 'Leshomo'],
            ['first_name' => 'Phaladi M.', 'last_name' => 'Sebate'],
            ['first_name' => 'T', 'last_name' => 'Masitwa'],
            ['first_name' => 'B', 'last_name' => 'Thamuku'],
            ['first_name' => 'R', 'last_name' => 'Nyathi'],
            ['first_name' => 'T.M.', 'last_name' => 'Masole'],
            ['first_name' => 'N.J.K.', 'last_name' => 'Mwandila'],
            ['first_name' => 'G', 'last_name' => 'More'],
            ['first_name' => 'T', 'last_name' => 'Selema'],
            ['first_name' => 'D', 'last_name' => 'Montlane'],
            ['first_name' => 'S', 'last_name' => 'Phiri'],
            ['first_name' => 'Dalene', 'last_name' => 'Marais'],
            ['first_name' => 'Magdeline', 'last_name' => 'Mannathoko'],
            ['first_name' => 'Irene', 'last_name' => 'Soko'],
            ['first_name' => 'Michael', 'last_name' => 'Gaotlhobogwe'],
            ['first_name' => 'Pat', 'last_name' => 'Baker'],
            ['first_name' => 'Mmaserame', 'last_name' => 'David'],
            ['first_name' => 'Daphne', 'last_name' => 'Paizee'],
            ['first_name' => 'L', 'last_name' => 'Banks'],
            ['first_name' => 'Barolong', 'last_name' => 'Seboni'],
            ['first_name' => 'Mirna', 'last_name' => 'Lawrence'],
            ['first_name' => 'D', 'last_name' => 'Jankie'],
            ['first_name' => 'T. V.', 'last_name' => 'Moumakwa'],
            ['first_name' => 'S', 'last_name' => 'Tsopito'],
            ['first_name' => 'Unity', 'last_name' => 'Dow'],
            ['first_name' => 'L', 'last_name' => 'Mokgwathise'],
            ['first_name' => 'M', 'last_name' => 'Mokgwathise'],
            ['first_name' => 'G', 'last_name' => 'Malinga'],
            ['first_name' => 'Simonds T.A.', 'last_name' => 'Bamfo'],
            ['first_name' => 'Lebuile', 'last_name' => 'Dimotowe'],
            ['first_name' => 'Bruce', 'last_name' => 'Kelesitse'],
            ['first_name' => 'Gaetlhaolwe', 'last_name' => 'Dikobe'],
            ['first_name' => 'Bernadette', 'last_name' => 'Romo'],
            ['first_name' => 'S.T.', 'last_name' => 'Amoah-Bamfo'],
            ['first_name' => 'M.L.', 'last_name' => 'Menyatso'],
            ['first_name' => 'M', 'last_name' => 'Maremela'],
            ['first_name' => 'M', 'last_name' => 'Morapedi'],
            ['first_name' => 'Grace', 'last_name' => 'Setlalekgosi-Khan'],
            ['first_name' => 'K. I.', 'last_name' => 'Dintwe'],
            ['first_name' => 'Tefo', 'last_name' => 'Malokana'],
            ['first_name' => 'Ludo', 'last_name' => 'Polelo'],
            ['first_name' => 'R', 'last_name' => 'Baitsewe'],
            ['first_name' => 'B', 'last_name' => 'Lekuntwane'],
            ['first_name' => 'Connie S', 'last_name' => 'Mankandla'],
            ['first_name' => 'M', 'last_name' => 'Mahabile'],
            ['first_name' => 'C', 'last_name' => 'Matlhare'],
            ['first_name' => 'M', 'last_name' => 'Nsinamwa'],
            ['first_name' => 'R', 'last_name' => 'Mlilo'],
            ['first_name' => 'T', 'last_name' => 'Kgakole'],
            ['first_name' => 'M', 'last_name' => 'Manthe'],
            ['first_name' => 'J', 'last_name' => 'Kasozi'],
            ['first_name' => 'G', 'last_name' => 'McLeod'],
            ['first_name' => 'L', 'last_name' => 'Matthews'],
            ['first_name' => 'T', 'last_name' => 'Simela'],
            ['first_name' => 'J', 'last_name' => 'Chengeta'],
            ['first_name' => 'Tinieri', 'last_name' => 'Maeresera'],
            ['first_name' => 'Keorapetse', 'last_name' => 'Moloi'],
            ['first_name' => 'Vistah J', 'last_name' => 'Mudenda'],
            ['first_name' => 'G.T.', 'last_name' => 'More'],
            ['first_name' => 'Edwin', 'last_name' => 'Dichaba'],
            ['first_name' => 'D', 'last_name' => 'Gaolebogwe'],
            ['first_name' => 'K', 'last_name' => 'Molebatsi'],
            ['first_name' => 'Mwelwa Z', 'last_name' => 'Mwansa'],
            ['first_name' => 'Clifford', 'last_name' => 'Marambo'],
            ['first_name' => 'Brian', 'last_name' => 'Dill'],
            ['first_name' => 'Bushy Percy', 'last_name' => 'Mmatli'],
            ['first_name' => 'Dimane', 'last_name' => 'Mpoeleng'],
            ['first_name' => 'R', 'last_name' => 'Moalosi'],
            ['first_name' => 'R.R.', 'last_name' => 'Ketlhaotswe'],
            ['first_name' => 'E. Y.', 'last_name' => 'Brenyah'],
            ['first_name' => 'K. P.', 'last_name' => 'Selwe'],
            ['first_name' => 'P. H.', 'last_name' => 'Mhundwa'],
            ['first_name' => 'P. T.', 'last_name' => 'Tihowe'],
            ['first_name' => 'T. Ndebele', 'last_name' => 'Dube'],
            ['first_name' => 'Wame', 'last_name' => 'Molefhe'],
            ['first_name' => 'Rose', 'last_name' => 'Letsholo'],
            ['first_name' => 'Sylvia', 'last_name' => 'Honnor'],
            ['first_name' => 'Heather', 'last_name' => 'Mascie'],
            ['first_name' => 'L. R.', 'last_name' => 'Mberengwa'],
            ['first_name' => 'S', 'last_name' => 'Trivedi'],
            ['first_name' => 'G', 'last_name' => 'Phuthego'],
            ['first_name' => 'M', 'last_name' => 'Mokakapadi'],
            ['first_name' => 'M', 'last_name' => 'Timile'],
            ['first_name' => 'P', 'last_name' => 'Chakalisa'],
            ['first_name' => 'AV', 'last_name' => 'Siduna'],
            ['first_name' => 'D', 'last_name' => 'Khame'],
            ['first_name' => 'O', 'last_name' => 'Setlhare'],
            ['first_name' => 'D', 'last_name' => 'Fourie'],
            ['first_name' => 'J', 'last_name' => 'Marchant'],
            ['first_name' => 'S', 'last_name' => 'van Ryswyck'],
            ['first_name' => 'C', 'last_name' => 'Wyeth'],
            ['first_name' => 'C', 'last_name' => 'Malense'],
            ['first_name' => 'U', 'last_name' => 'Mokobi'],
            ['first_name' => 'S', 'last_name' => 'Letsholo'],
            ['first_name' => 'V', 'last_name' => 'Anderson'],
            ['first_name' => 'B', 'last_name' => 'Nkala'],
            ['first_name' => 'G', 'last_name' => 'Mogapi'],
            ['first_name' => 'D', 'last_name' => 'Timile'],
            ['first_name' => 'R', 'last_name' => 'Brooksbank'],
            ['first_name' => 'D', 'last_name' => 'du Plessis'],
            ['first_name' => 'Atang', 'last_name' => 'Tshukudu'],
            ['first_name' => 'Moetsi R. T.', 'last_name' => 'Makgeng'],
            ['first_name' => 'G.T.', 'last_name' => 'Tsayang'],
            ['first_name' => 'V', 'last_name' => 'Ngongola'],
            ['first_name' => 'P', 'last_name' => 'Montsho'],
            ['first_name' => 'Robert', 'last_name' => 'Kowa'],
            ['first_name' => 'Constance', 'last_name' => 'Mankandla'],
            ['first_name' => 'C', 'last_name' => 'Matlhare'],
            ['first_name' => 'M', 'last_name' => 'Nsinamwa'],
            ['first_name' => 'M', 'last_name' => 'Mahabile'],
            ['first_name' => 'R', 'last_name' => 'Mlilo'],
            ['first_name' => 'E', 'last_name' => 'Kgakole'],
            ['first_name' => 'M', 'last_name' => 'Manthe'],
            ['first_name' => 'J', 'last_name' => 'Kasozi'],
            ['first_name' => 'G', 'last_name' => 'McLeod'],
            ['first_name' => 'L', 'last_name' => 'Mathews'],
            ['first_name' => 'T', 'last_name' => 'Simela'],
            ['first_name' => 'J', 'last_name' => 'Chengeta'],
            ['first_name' => 'D', 'last_name' => 'Gaolebogwe'],
            ['first_name' => 'K', 'last_name' => 'Molebatsi'],
            ['first_name' => 'A', 'last_name' => 'Kampamba'],
            ['first_name' => 'D', 'last_name' => 'van Suilichem'],
            ['first_name' => 'C', 'last_name' => 'Noomé'],
            ['first_name' => 'R', 'last_name' => 'Moalosi'],
            ['first_name' => 'R. R.', 'last_name' => 'Ketlhaotswe'],
            ['first_name' => 'E. Y.', 'last_name' => 'Brenyah'],
            ['first_name' => 'K.P.', 'last_name' => 'Selwe'],
            ['first_name' => 'P.T.', 'last_name' => 'Tihowe'],
            ['first_name' => 'B', 'last_name' => 'Kgope'],
            ['first_name' => 'Heather', 'last_name' => 'Mascie Taylor'],
            ['first_name' => 'S.L.', 'last_name' => 'Botshoma'],
            ['first_name' => 'L', 'last_name' => 'Chipazi'],
            ['first_name' => 'M', 'last_name' => 'Modisa'],
            ['first_name' => 'M', 'last_name' => 'Peloewetse'],
            ['first_name' => 'O', 'last_name' => 'Makgonatsotlhe'],
            ['first_name' => 'A', 'last_name' => 'Themba'],
            ['first_name' => 'Miriam', 'last_name' => 'Maroba'],
            ['first_name' => 'Naomi', 'last_name' => 'Mnthali'],
            ['first_name' => 'Tiny', 'last_name' => 'Sento-Pelaelo'],
            ['first_name' => 'Lois R.', 'last_name' => 'Mberengwa'],
            ['first_name' => 'Shikha', 'last_name' => 'Trivedi'],
            ['first_name' => 'Tebogo V.', 'last_name' => 'Molebatsi'],
            ['first_name' => 'M', 'last_name' => 'Mokakapadi'],
            ['first_name' => 'M', 'last_name' => 'Timile'],
            ['first_name' => 'P', 'last_name' => 'Chakalisa'],
            ['first_name' => 'D', 'last_name' => 'Khame'],
            ['first_name' => 'O', 'last_name' => 'Setlhare'],
            ['first_name' => 'AV', 'last_name' => 'Siduna'],
            ['first_name' => 'K', 'last_name' => 'Maphala'],
            ['first_name' => 'D', 'last_name' => 'Fourie'],
            ['first_name' => 'J', 'last_name' => 'Marchant'],
            ['first_name' => 'S', 'last_name' => 'van Ryswyck'],
            ['first_name' => 'C', 'last_name' => 'Wyeth'],
            ['first_name' => 'C', 'last_name' => 'Malense'],
            ['first_name' => 'U', 'last_name' => 'Mokobi'],
            ['first_name' => 'V', 'last_name' => 'Anderson'],
            ['first_name' => 'G', 'last_name' => 'Mogapi'],
            ['first_name' => 'D', 'last_name' => 'Timile'],
            ['first_name' => 'R', 'last_name' => 'Brooksbank'],
            ['first_name' => 'D', 'last_name' => 'du Plessis'],
            ['first_name' => 'R.B.', 'last_name' => 'Prophet'],
            ['first_name' => 'M', 'last_name' => 'Motswiri'],
            ['first_name' => 'M', 'last_name' => 'Tshukudu'],
            ['first_name' => 'M', 'last_name' => 'Mpugwa'],
            ['first_name' => 'O', 'last_name' => 'Motsomi'],
            ['first_name' => 'B', 'last_name' => 'Mbakile'],
            ['first_name' => 'R. T.', 'last_name' => 'Makgeng'],
            ['first_name' => 'Rosemary', 'last_name' => 'Ford'],
            ['first_name' => 'Alois', 'last_name' => 'Mlambo'],
            ['first_name' => 'Andrew', 'last_name' => 'Molwane'],
            ['first_name' => 'V', 'last_name' => 'Ngongola'],
            ['first_name' => 'G', 'last_name' => 'Gatsha'],
            ['first_name' => 'G.T.', 'last_name' => 'Tsayang'],
        ];

        $school_type = DB::table('school_setup')->pluck('type')->first();
        $authors = ($school_type === 'Primary') ? $authorsPrimary : $authorsJunior;
        
        $chunkedAuthors = array_chunk($authors, 100);
        DB::beginTransaction();
        
        try {
            foreach ($chunkedAuthors as $chunk) {
                DB::table(self::TABLE_NAME)->insertOrIgnore($chunk);
            }
            DB::commit();
        } catch (\Exception $e) {
            DB::rollBack();
            Log::error('Error inserting authors: ' . $e->getMessage());
        }        
    }

    public function down(){
        Schema::dropIfExists(self::TABLE_NAME);
    }
};