<?php

return [
    'stages' => [
        'scope' => [
            ['key' => 'institution_legal_name', 'label' => 'Legal institution name', 'type' => 'text', 'requirement' => 'R', 'min_length' => 2, 'max_length' => 180],
            ['key' => 'institution_common_name', 'label' => 'Trading/common name', 'type' => 'text', 'requirement' => 'O', 'max_length' => 180],
            ['key' => 'prepared_by_name', 'label' => 'Prepared by', 'type' => 'text', 'requirement' => 'R'],
            ['key' => 'prepared_by_position', 'label' => 'Prepared by position', 'type' => 'text', 'requirement' => 'R'],
            ['key' => 'submission_date', 'label' => 'Submission date', 'type' => 'date', 'requirement' => 'R', 'not_future' => true],
            ['key' => 'target_go_live', 'label' => 'Target go-live period', 'type' => 'month', 'requirement' => 'R'],
            ['key' => 'secure_transfer_method', 'label' => 'Secure file-transfer method', 'type' => 'text', 'requirement' => 'C', 'help' => 'Complete this only if files will be sent outside the wizard.'],
            ['key' => 'authorized_submitter_confirmed', 'label' => 'I confirm that I am authorized to submit this setup information.', 'type' => 'boolean', 'requirement' => 'R', 'must_be_true' => true],
            ['key' => 'privacy_requirements_acknowledged', 'label' => 'I confirm that sensitive files will be redacted and transferred through an agreed secure method.', 'type' => 'boolean', 'requirement' => 'R', 'must_be_true' => true],
        ],
        'institution' => [
            ['key' => 'registration_number', 'label' => 'Registration number', 'type' => 'text', 'requirement' => 'R'],
            ['key' => 'accreditation_body', 'label' => 'Accreditation body', 'type' => 'text', 'requirement' => 'R'],
            ['key' => 'provider_number', 'label' => 'Provider number', 'type' => 'text', 'requirement' => 'R'],
            ['key' => 'ownership_type', 'label' => 'Ownership', 'type' => 'select', 'requirement' => 'R', 'options' => ['public' => 'Public', 'private_for_profit' => 'Private for profit', 'private_not_for_profit' => 'Private not for profit', 'faith_based' => 'Faith-based', 'community_trust' => 'Community/trust', 'other' => 'Other']],
            ['key' => 'ownership_other', 'label' => 'Other ownership description', 'type' => 'text', 'requirement' => 'C', 'required_when' => ['field' => 'ownership_type', 'equals' => 'other']],
            ['key' => 'institution_categories', 'label' => 'Institution category', 'type' => 'multiselect', 'requirement' => 'R', 'options' => ['higher_education' => 'Higher education', 'vocational' => 'Vocational/training', 'professional' => 'Professional education', 'health_sciences' => 'Health sciences', 'teacher_education' => 'Teacher education', 'research' => 'Research-led', 'other' => 'Other'], 'min_items' => 1],
            ['key' => 'awards_offered', 'label' => 'Awards offered', 'type' => 'multiselect', 'requirement' => 'R', 'options' => ['certificate' => 'Certificate', 'diploma' => 'Diploma', 'degree' => 'Degree', 'short_course' => 'Short course', 'other' => 'Other'], 'min_items' => 1],
            ['key' => 'mandate_description', 'label' => 'Mandate, specialization and target population', 'type' => 'textarea', 'requirement' => 'R', 'min_length' => 20],
            ['key' => 'campuses', 'label' => 'Campuses and delivery sites', 'type' => 'repeatable', 'requirement' => 'R', 'min_items' => 1, 'fields' => [
                ['key' => 'code', 'label' => 'Campus/site code', 'type' => 'text', 'requirement' => 'R'],
                ['key' => 'name', 'label' => 'Campus/site name', 'type' => 'text', 'requirement' => 'R'],
                ['key' => 'physical_location', 'label' => 'Physical location', 'type' => 'text', 'requirement' => 'R'],
                ['key' => 'programmes_offered', 'label' => 'Programmes offered at this site', 'type' => 'text', 'requirement' => 'O'],
                ['key' => 'active', 'label' => 'Active campus', 'type' => 'boolean', 'requirement' => 'R', 'default' => true],
            ]],
            ['key' => 'responsible_contacts', 'label' => 'Responsible contacts', 'type' => 'repeatable', 'requirement' => 'R', 'min_items' => 1, 'help' => 'Required: include at least one contact with the role Academic lead.', 'fields' => [
                ['key' => 'role', 'label' => 'Contact role', 'type' => 'select', 'requirement' => 'R', 'options' => ['executive_sponsor' => 'Executive sponsor', 'registrar' => 'Registrar', 'academic_lead' => 'Academic lead', 'examinations_lead' => 'Examinations lead', 'admissions_lead' => 'Admissions lead', 'it_data_lead' => 'IT/data lead', 'finance_lead' => 'Finance lead', 'other' => 'Other']],
                ['key' => 'name', 'label' => 'Name', 'type' => 'text', 'requirement' => 'R'],
                ['key' => 'position', 'label' => 'Position', 'type' => 'text', 'requirement' => 'R'],
                ['key' => 'email', 'label' => 'Email', 'type' => 'email', 'requirement' => 'R'],
                ['key' => 'telephone', 'label' => 'Telephone', 'type' => 'text', 'requirement' => 'R'],
                ['key' => 'is_primary', 'label' => 'Primary contact', 'type' => 'boolean', 'requirement' => 'R'],
            ]],
            ['key' => 'academic_structure', 'label' => 'Academic structure description', 'type' => 'textarea', 'requirement' => 'R', 'min_length' => 20, 'help' => 'Describe faculty/school → department → programme → level → semester → module.'],
            ['key' => 'structure_varies_by_campus', 'label' => 'Does the academic structure vary by campus?', 'control_label' => 'Yes, the academic structure varies by campus', 'type' => 'boolean', 'requirement' => 'O', 'collapsible' => true],
            ['key' => 'campus_structure_differences', 'label' => 'Campus-specific structure differences', 'type' => 'textarea', 'requirement' => 'C', 'required_when' => ['field' => 'structure_varies_by_campus', 'equals' => true]],
            ['key' => 'academic_year_pattern', 'label' => 'Academic year pattern', 'type' => 'select', 'requirement' => 'R', 'options' => ['calendar' => 'Calendar year', 'split_year' => 'Split year', 'rolling_intake' => 'Rolling intake', 'block_trimester' => 'Block/trimester', 'other' => 'Other']],
            ['key' => 'academic_year_pattern_other', 'label' => 'Other year pattern', 'type' => 'text', 'requirement' => 'C', 'required_when' => ['field' => 'academic_year_pattern', 'equals' => 'other']],
            ['key' => 'academic_year_naming', 'label' => 'Academic year naming', 'type' => 'text', 'requirement' => 'R', 'help' => 'Example: 2026 or 2026/2027.'],
            ['key' => 'academic_year_start', 'label' => 'Academic year start', 'type' => 'date', 'requirement' => 'R'],
            ['key' => 'academic_year_end', 'label' => 'Academic year end', 'type' => 'date', 'requirement' => 'R'],
            ['key' => 'semesters_per_year', 'label' => 'Semesters/periods per year', 'type' => 'number', 'requirement' => 'R', 'min' => 1, 'step' => 1],
            ['key' => 'primary_intakes', 'label' => 'Primary intakes', 'type' => 'text', 'requirement' => 'R', 'help' => 'List months or dates.'],
            ['key' => 'markbook_lock_rule', 'label' => 'Markbook lock rule', 'type' => 'textarea', 'requirement' => 'O'],
            ['key' => 'academic_periods', 'label' => 'Academic periods', 'type' => 'repeatable', 'requirement' => 'O', 'min_items' => 1, 'collapsible' => true, 'fields' => [
                ['key' => 'period', 'label' => 'Period number/code', 'type' => 'text', 'requirement' => 'R'],
                ['key' => 'official_label', 'label' => 'Official label', 'type' => 'text', 'requirement' => 'R'],
                ['key' => 'start_date', 'label' => 'Start date', 'type' => 'date', 'requirement' => 'R'],
                ['key' => 'end_date', 'label' => 'End date', 'type' => 'date', 'requirement' => 'R'],
                ['key' => 'teaching_weeks', 'label' => 'Teaching weeks', 'type' => 'number', 'requirement' => 'R', 'min' => 0, 'step' => 1],
                ['key' => 'exam_weeks', 'label' => 'Exam weeks', 'type' => 'number', 'requirement' => 'R', 'min' => 0, 'step' => 1],
                ['key' => 'results_release', 'label' => 'Results release rule/date', 'type' => 'text', 'requirement' => 'R'],
            ]],
            ['key' => 'delivery_modes', 'label' => 'Teaching/attendance modes', 'type' => 'multiselect', 'requirement' => 'R', 'options' => ['full_time' => 'Full-time', 'part_time' => 'Part-time', 'campus' => 'Campus', 'online' => 'Online', 'blended' => 'Blended', 'distance' => 'Distance', 'evening_weekend' => 'Evening/weekend', 'block' => 'Block', 'clinical_practical' => 'Clinical/practical'], 'min_items' => 1],
            ['key' => 'registration_rules', 'label' => 'Add/drop and registration rules', 'type' => 'textarea', 'requirement' => 'R', 'min_length' => 20],
            ['key' => 'faculties_departments', 'label' => 'Faculties and departments', 'type' => 'repeatable', 'requirement' => 'O', 'fields' => [
                ['key' => 'faculty_code', 'label' => 'Faculty/school code', 'type' => 'text', 'requirement' => 'R'],
                ['key' => 'faculty_name', 'label' => 'Faculty/school name', 'type' => 'text', 'requirement' => 'R'],
                ['key' => 'department_code', 'label' => 'Department code', 'type' => 'text', 'requirement' => 'O'],
                ['key' => 'department_name', 'label' => 'Department name', 'type' => 'text', 'requirement' => 'O'],
                ['key' => 'head_owner', 'label' => 'Head/owner', 'type' => 'text', 'requirement' => 'O'],
            ]],
        ],
        'programmes' => [
            ['key' => 'portfolio_rules_shared', 'label' => 'Portfolio-wide rules shared across programmes', 'type' => 'multiselect', 'requirement' => 'R', 'options' => ['grading' => 'Grading', 'gpa' => 'GPA', 'progression' => 'Progression', 'retake' => 'Retake', 'assessment' => 'Assessment', 'calendar' => 'Calendar', 'result_slip' => 'Result slip', 'transcript' => 'Transcript'], 'min_items' => 1],
            ['key' => 'portfolio_exceptions', 'label' => 'Programme-specific exceptions', 'type' => 'repeatable', 'requirement' => 'O', 'fields' => [
                ['key' => 'programme_code', 'label' => 'Programme code', 'type' => 'text', 'requirement' => 'R'],
                ['key' => 'rule_area', 'label' => 'Rule area', 'type' => 'text', 'requirement' => 'R'],
                ['key' => 'exception', 'label' => 'Exception', 'type' => 'textarea', 'requirement' => 'R'],
                ['key' => 'effective_date', 'label' => 'Effective date', 'type' => 'date', 'requirement' => 'R'],
                ['key' => 'approving_authority', 'label' => 'Approving authority', 'type' => 'text', 'requirement' => 'R'],
            ]],
            ['key' => 'programmes', 'label' => 'Programme register', 'type' => 'repeatable', 'requirement' => 'R', 'min_items' => 1, 'fields' => [
                ['key' => 'code', 'label' => 'Programme code', 'type' => 'text', 'requirement' => 'R'],
                ['key' => 'name', 'label' => 'Programme name', 'type' => 'text', 'requirement' => 'R'],
                ['key' => 'approved_title', 'label' => 'Full approved title', 'type' => 'text', 'requirement' => 'R'],
                ['key' => 'award_type', 'label' => 'Award/type', 'type' => 'select', 'requirement' => 'R', 'options' => ['certificate' => 'Certificate', 'diploma' => 'Diploma', 'degree' => 'Degree', 'other' => 'Other']],
                ['key' => 'nqf_level', 'label' => 'NQF level', 'type' => 'text', 'requirement' => 'R', 'info' => [
                    'title' => 'Botswana NCQF guide',
                    'items' => [
                        'Certificate I — Level 1',
                        'Certificate II — Level 2',
                        'Certificate III — Level 3',
                        'Certificate IV — Level 4',
                        'Certificate V — Level 5',
                        'Diploma — Level 6',
                        'Bachelor’s degree — Level 7',
                        'Bachelor’s Honours degree — Level 8',
                        'Master’s degree — Level 9',
                        'Doctoral degree — Level 10',
                    ],
                ]],
                ['key' => 'duration', 'label' => 'Duration', 'type' => 'text', 'requirement' => 'R'],
                ['key' => 'mode', 'label' => 'Mode', 'type' => 'select', 'requirement' => 'R', 'options' => ['full_time' => 'Full-time', 'part_time' => 'Part-time', 'online' => 'Online', 'blended' => 'Blended', 'other' => 'Other']],
                ['key' => 'campus', 'label' => 'Campus/site', 'type' => 'text', 'requirement' => 'R'],
                ['key' => 'active_intakes', 'label' => 'Active intakes', 'type' => 'text', 'requirement' => 'R', 'help' => 'List the months or dates when students can start this programme, for example January and August.'],
                ['key' => 'faculty', 'label' => 'Faculty', 'type' => 'text', 'requirement' => 'R'],
                ['key' => 'department', 'label' => 'Department head', 'type' => 'text', 'requirement' => 'O'],
                ['key' => 'purpose', 'label' => 'Programme purpose and outcomes', 'type' => 'textarea', 'requirement' => 'O', 'min_length' => 20],
                ['key' => 'entry_requirements', 'label' => 'Minimum entry requirements', 'type' => 'textarea', 'requirement' => 'R', 'min_length' => 20],
                ['key' => 'completion_requirements', 'label' => 'Graduation/completion requirements', 'type' => 'textarea', 'requirement' => 'R', 'min_length' => 20],
                ['key' => 'active', 'label' => 'Active programme', 'type' => 'boolean', 'requirement' => 'R', 'default' => true],
            ]],
        ],
        'curriculum' => [
            ['key' => 'curriculum_in_scope', 'label' => 'Curriculum configuration is in scope for this implementation.', 'type' => 'boolean', 'requirement' => 'O', 'collapsible_group' => 'curriculum_scope', 'collapsible_group_label' => 'Curriculum scope and handoff'],
            ['key' => 'curriculum_exclusion_reason', 'label' => 'If curriculum is out of scope, explain the implementation handoff or migration plan.', 'type' => 'textarea', 'requirement' => 'O', 'collapsible_group' => 'curriculum_scope', 'min_length' => 20],
            ['key' => 'curriculum_versions', 'label' => 'Curriculum versions', 'type' => 'repeatable', 'requirement' => 'C', 'required_when' => ['field' => 'curriculum_in_scope', 'equals' => true], 'min_items' => 1, 'fields' => [
                ['key' => 'programme_code', 'label' => 'Programme code', 'type' => 'text', 'requirement' => 'R'],
                ['key' => 'code', 'label' => 'Curriculum version code', 'type' => 'text', 'requirement' => 'R'],
                ['key' => 'name', 'label' => 'Curriculum version name', 'type' => 'text', 'requirement' => 'R'],
                ['key' => 'effective_from', 'label' => 'Effective from', 'type' => 'date', 'requirement' => 'R'],
                ['key' => 'effective_to', 'label' => 'Effective to', 'type' => 'date', 'requirement' => 'O'],
                ['key' => 'total_credits', 'label' => 'Total credits', 'type' => 'number', 'requirement' => 'R', 'min' => 0, 'step' => '0.01'],
                ['key' => 'modules', 'label' => 'Modules', 'type' => 'repeatable', 'requirement' => 'R', 'min_items' => 1, 'fields' => [
                    ['key' => 'code', 'label' => 'Module code', 'type' => 'text', 'requirement' => 'R'],
                    ['key' => 'title', 'label' => 'Module title', 'type' => 'text', 'requirement' => 'R'],
                    ['key' => 'year_level', 'label' => 'Year/level', 'type' => 'text', 'requirement' => 'R'],
                    ['key' => 'semester', 'label' => 'Semester', 'type' => 'text', 'requirement' => 'R'],
                    ['key' => 'credits', 'label' => 'Credits', 'type' => 'number', 'requirement' => 'R', 'min' => 0, 'step' => '0.01'],
                    ['key' => 'core_elective', 'label' => 'Core/elective', 'type' => 'select', 'requirement' => 'R', 'options' => ['core' => 'Core', 'elective' => 'Elective', 'compulsory_non_credit' => 'Compulsory non-credit', 'other' => 'Other']],
                    ['key' => 'prerequisite', 'label' => 'Prerequisite/co-requisite', 'type' => 'text', 'requirement' => 'O'],
                    ['key' => 'theory_practical_hours', 'label' => 'Theory/practical hours', 'type' => 'text', 'requirement' => 'O'],
                ]],
            ]],
            ['key' => 'elective_pools', 'label' => 'Elective pools', 'type' => 'repeatable', 'requirement' => 'O', 'fields' => [
                ['key' => 'code', 'label' => 'Pool code', 'type' => 'text', 'requirement' => 'R'],
                ['key' => 'name', 'label' => 'Pool name', 'type' => 'text', 'requirement' => 'R'],
                ['key' => 'eligible_students', 'label' => 'Eligible students', 'type' => 'textarea', 'requirement' => 'R'],
                ['key' => 'modules', 'label' => 'Modules in pool', 'type' => 'text', 'requirement' => 'R'],
                ['key' => 'selection_rule', 'label' => 'Selection rule', 'type' => 'textarea', 'requirement' => 'R'],
            ]],
            ['key' => 'practical_requirements', 'label' => 'Practical/clinical requirements', 'type' => 'repeatable', 'requirement' => 'O', 'fields' => [
                ['key' => 'type', 'label' => 'Requirement type', 'type' => 'text', 'requirement' => 'R'],
                ['key' => 'hours_credits', 'label' => 'Required hours/credits', 'type' => 'text', 'requirement' => 'R'],
                ['key' => 'completion_point', 'label' => 'When completed', 'type' => 'text', 'requirement' => 'R'],
                ['key' => 'pass_rule', 'label' => 'Pass/sign-off rule', 'type' => 'textarea', 'requirement' => 'R'],
                ['key' => 'blocks_progression', 'label' => 'Blocks progression', 'type' => 'boolean', 'requirement' => 'R'],
                ['key' => 'blocks_graduation', 'label' => 'Blocks graduation', 'type' => 'boolean', 'requirement' => 'R'],
            ]],
        ],
        'assessment' => [
            ['key' => 'assessment_types', 'label' => 'Assessment categories used', 'type' => 'multiselect', 'requirement' => 'R', 'options' => ['ca' => 'Continuous assessment', 'assignments' => 'Assignments', 'tests' => 'Tests', 'quizzes' => 'Quizzes', 'projects' => 'Projects', 'practical' => 'Practical', 'clinical' => 'Clinical', 'portfolio' => 'Portfolio', 'presentation' => 'Presentation', 'exam' => 'Examination', 'other' => 'Other'], 'min_items' => 1],
            ['key' => 'assessment_components', 'label' => 'Assessment components', 'type' => 'repeatable', 'requirement' => 'O', 'min_items' => 1, 'collapsible' => true, 'fields' => [
                ['key' => 'category', 'label' => 'Category', 'type' => 'text', 'requirement' => 'R'],
                ['key' => 'sequence', 'label' => 'Typical component/sequence', 'type' => 'text', 'requirement' => 'R'],
                ['key' => 'marked_out_of', 'label' => 'Marked out of', 'type' => 'number', 'requirement' => 'R', 'min' => 1, 'step' => '0.01'],
                ['key' => 'weight_percent', 'label' => 'Weight percentage', 'type' => 'number', 'requirement' => 'R', 'min' => 0, 'max' => 100, 'step' => '0.01'],
                ['key' => 'minimum_mark', 'label' => 'Minimum component mark', 'type' => 'number', 'requirement' => 'O', 'min' => 0, 'max' => 100, 'step' => '0.01'],
                ['key' => 'compulsory', 'label' => 'Compulsory', 'type' => 'boolean', 'requirement' => 'R'],
                ['key' => 'shown_on_result_slip', 'label' => 'Shown on result slip', 'type' => 'boolean', 'requirement' => 'R'],
            ]],
            ['key' => 'module_mark_formula', 'label' => 'Final module mark formula', 'type' => 'textarea', 'requirement' => 'O', 'min_length' => 20, 'collapsible_group' => 'assessment_rules', 'collapsible_group_label' => 'Assessment and GPA rules'],
            ['key' => 'module_pass_conditions', 'label' => 'Module pass conditions', 'type' => 'textarea', 'requirement' => 'O', 'min_length' => 20, 'collapsible_group' => 'assessment_rules'],
            ['key' => 'default_module_pass_mark', 'label' => 'Default module pass mark', 'type' => 'number', 'requirement' => 'O', 'min' => 0, 'max' => 100, 'step' => '0.01', 'collapsible_group' => 'assessment_rules'],
            ['key' => 'examination_subminimum', 'label' => 'Examination sub-minimum', 'type' => 'number', 'requirement' => 'O', 'min' => 0, 'max' => 100, 'step' => '0.01', 'collapsible_group' => 'assessment_rules', 'info' => ['title' => 'What is an examination sub-minimum?', 'items' => ['The minimum examination mark a learner must achieve even if the overall module mark is high enough to pass.', 'Example: enter 40 when a learner must score at least 40% in the examination.']]],
            ['key' => 'ca_subminimum', 'label' => 'Continuous-assessment sub-minimum', 'type' => 'number', 'requirement' => 'O', 'min' => 0, 'max' => 100, 'step' => '0.01', 'collapsible_group' => 'assessment_rules', 'info' => ['title' => 'What is a continuous-assessment sub-minimum?', 'items' => ['The minimum continuous-assessment mark a learner must achieve before the module can be passed.', 'Use this when a separate minimum applies to assignments, tests, projects or other coursework.']]],
            ['key' => 'rounding_rule', 'label' => 'Rounding precision and method', 'type' => 'text', 'requirement' => 'O', 'collapsible_group' => 'assessment_rules'],
            ['key' => 'attendance_threshold', 'label' => 'Attendance threshold', 'type' => 'text', 'requirement' => 'O', 'collapsible_group' => 'assessment_rules', 'info' => ['title' => 'What is the attendance threshold?', 'items' => ['The minimum attendance percentage or rule required before a learner may complete an assessment or module.', 'Enter the threshold and note any approved exceptions, such as clinical or practical attendance rules.']]],
            ['key' => 'missing_mark_outcome', 'label' => 'Missing mark outcome', 'type' => 'select', 'requirement' => 'O', 'options' => ['incomplete' => 'Incomplete', 'zero' => 'Zero', 'deferred' => 'Deferred', 'other' => 'Other'], 'collapsible_group' => 'assessment_rules'],
            ['key' => 'result_approval_mode', 'label' => 'Official result approval mode', 'type' => 'select', 'requirement' => 'O', 'options' => ['automatic' => 'Automatic', 'draft_then_board' => 'Draft then board', 'manual' => 'Manual', 'varies' => 'Varies by programme'], 'collapsible_group' => 'assessment_rules', 'info' => ['title' => 'What is official result approval?', 'items' => ['The step that makes marks and results official after they have been entered and moderated.', 'Choose whether approval is automatic, completed by a board, manual, or different by programme.']]],
            ['key' => 'mark_workflow', 'label' => 'Mark entry/moderation/approval workflow', 'type' => 'textarea', 'requirement' => 'O', 'min_length' => 20, 'collapsible_group' => 'assessment_rules'],
            ['key' => 'gpa_scale_maximum', 'label' => 'GPA scale maximum', 'type' => 'number', 'requirement' => 'O', 'min' => 0.01, 'step' => '0.01', 'collapsible_group' => 'assessment_rules'],
            ['key' => 'gpa_decimal_places', 'label' => 'GPA decimal places', 'type' => 'number', 'requirement' => 'O', 'min' => 0, 'max' => 4, 'step' => 1, 'collapsible_group' => 'assessment_rules'],
            ['key' => 'semester_gpa_calculated', 'label' => 'Semester GPA is calculated', 'type' => 'boolean', 'requirement' => 'O', 'collapsible_group' => 'assessment_rules'],
            ['key' => 'cumulative_gpa_calculated', 'label' => 'Cumulative GPA is calculated', 'type' => 'boolean', 'requirement' => 'O', 'collapsible_group' => 'assessment_rules'],
            ['key' => 'gpa_calculation_timing', 'label' => 'GPA calculation timing', 'type' => 'select', 'requirement' => 'O', 'options' => ['semester' => 'Semester', 'year' => 'Year', 'on_demand' => 'On demand', 'other' => 'Other'], 'collapsible_group' => 'assessment_rules', 'info' => ['title' => 'What is GPA calculation timing?', 'items' => ['When the system calculates or refreshes GPA results.', 'Choose after each semester, at the end of the year, on demand, or another institutional schedule.']]],
            ['key' => 'gpa_rounding_method', 'label' => 'GPA rounding method', 'type' => 'text', 'requirement' => 'O', 'collapsible_group' => 'assessment_rules', 'info' => ['title' => 'What is the GPA rounding method?', 'items' => ['How the GPA is rounded and displayed to users.', 'Example: round half up to two decimal places.']]],
            ['key' => 'gpa_method', 'label' => 'GPA method', 'type' => 'select', 'requirement' => 'O', 'options' => ['credit_weighted' => 'Credit-weighted', 'unweighted' => 'Unweighted', 'percentage' => 'Percentage', 'selected_credits' => 'Selected credits', 'other' => 'Other'], 'collapsible_group' => 'assessment_rules', 'info' => ['title' => 'What is the GPA method?', 'items' => ['The method used to combine module results into a GPA.', 'Choose credit-weighted, unweighted, percentage, selected credits, or another institutional method.']]],
            ['key' => 'semester_gpa_formula', 'label' => 'SGPA formula', 'type' => 'textarea', 'requirement' => 'O', 'min_length' => 20, 'collapsible_group' => 'assessment_rules'],
            ['key' => 'cumulative_gpa_formula', 'label' => 'CGPA formula', 'type' => 'textarea', 'requirement' => 'O', 'min_length' => 20, 'collapsible_group' => 'assessment_rules'],
            ['key' => 'grade_bands', 'label' => 'Grade bands', 'type' => 'repeatable', 'requirement' => 'R', 'min_items' => 1, 'fields' => [
                ['key' => 'minimum_mark', 'label' => 'Minimum mark', 'type' => 'number', 'requirement' => 'R', 'min' => 0, 'max' => 100, 'step' => '0.01'],
                ['key' => 'maximum_mark', 'label' => 'Maximum mark', 'type' => 'number', 'requirement' => 'R', 'min' => 0, 'max' => 100, 'step' => '0.01'],
                ['key' => 'letter_grade', 'label' => 'Letter/grade', 'type' => 'text', 'requirement' => 'R'],
                ['key' => 'grade_points', 'label' => 'Grade points', 'type' => 'number', 'requirement' => 'R', 'min' => 0, 'step' => '0.01'],
                ['key' => 'result_status', 'label' => 'Result status', 'type' => 'text', 'requirement' => 'R'],
                ['key' => 'description', 'label' => 'Meaning', 'type' => 'text', 'requirement' => 'O'],
            ]],
            ['key' => 'gpa_inclusion_rules', 'label' => 'GPA inclusion/exclusion rules', 'type' => 'textarea', 'requirement' => 'O', 'min_length' => 20, 'collapsible' => true, 'info' => ['title' => 'What are GPA inclusion/exclusion rules?', 'items' => ['Explain which modules, marks or credits count toward GPA and which are left out.', 'Include exceptions such as pass/fail modules, non-credit modules, repeated modules or transferred credits.']]],
        ],
        'progression' => [
            ['key' => 'progression_evaluation_timing', 'label' => 'When progression is evaluated', 'type' => 'select', 'requirement' => 'R', 'options' => ['semester' => 'Semester', 'year' => 'Year', 'programme_level' => 'Programme level', 'board' => 'Board', 'varies' => 'Varies']],
            ['key' => 'progression_inputs', 'label' => 'Progression inputs', 'type' => 'multiselect', 'requirement' => 'R', 'options' => ['gpa' => 'GPA', 'credits' => 'Credits', 'failures' => 'Failures', 'practicals' => 'Practicals', 'prerequisites' => 'Prerequisites', 'attendance' => 'Attendance', 'attempts' => 'Attempts', 'other' => 'Other'], 'min_items' => 1],
            ['key' => 'progression_rules', 'label' => 'Progression decision matrix', 'type' => 'repeatable', 'requirement' => 'O', 'min_items' => 1, 'collapsible' => true, 'info' => ['title' => 'What is the progression decision matrix?', 'items' => ['List the conditions that lead to a progression decision and the action that follows each condition.', 'Add one row for each outcome, such as progress, repeat, probation or withdrawal.']], 'fields' => [
                ['key' => 'condition', 'label' => 'Condition/trigger', 'type' => 'text', 'requirement' => 'R', 'info' => ['title' => 'What is the condition or trigger?', 'items' => ['State the event that starts this rule, such as a GPA range, failed modules or an attendance issue.']]],
                ['key' => 'threshold', 'label' => 'Exact threshold/rule', 'type' => 'textarea', 'requirement' => 'R', 'info' => ['title' => 'What is the exact threshold or rule?', 'items' => ['Give the precise cutoff or logic used to apply the rule.', 'Example: CGPA below 2.0 or more than two failed core modules.']]],
                ['key' => 'decision_code', 'label' => 'Decision code', 'type' => 'text', 'requirement' => 'R', 'info' => ['title' => 'What is the decision code?', 'items' => ['Enter a short unique code used to identify this outcome in reports and workflows.', 'Example: PROGRESS, REPEAT or PROBATION.']]],
                ['key' => 'student_label', 'label' => 'Student-facing label', 'type' => 'text', 'requirement' => 'R', 'info' => ['title' => 'What is the student-facing label?', 'items' => ['Enter the clear wording learners should see for this outcome.', 'Example: Eligible to progress or Repeat the semester.']]],
                ['key' => 'may_register_next', 'label' => 'May register next semester', 'type' => 'boolean', 'requirement' => 'R', 'info' => ['title' => 'May the learner register next semester?', 'items' => ['Select this when the outcome allows the learner to register for the next semester or period.']]],
                ['key' => 'approval_action', 'label' => 'Approval/action', 'type' => 'textarea', 'requirement' => 'R', 'info' => ['title' => 'What approval or action is required?', 'items' => ['Describe the next step, responsible authority and any required approval or restriction.']]],
            ]],
            ['key' => 'progression_rule_precedence', 'label' => 'Rule precedence', 'type' => 'textarea', 'requirement' => 'O', 'min_length' => 20, 'collapsible_group' => 'progression_graduation_rules', 'collapsible_group_label' => 'Progression, retakes and graduation rules', 'info' => ['title' => 'What is rule precedence?', 'items' => ['Explain which rule takes priority when more than one progression rule applies at the same time.']]],
            ['key' => 'maximum_attempts', 'label' => 'Maximum total attempts', 'type' => 'text', 'requirement' => 'O', 'collapsible_group' => 'progression_graduation_rules', 'collapsible_group_label' => 'Progression, retakes and graduation rules', 'info' => ['title' => 'What are maximum total attempts?', 'items' => ['Enter the maximum number of times a learner may attempt a module, assessment or stage.']]],
            ['key' => 'approval_after_attempts', 'label' => 'Approval required after', 'type' => 'text', 'requirement' => 'O', 'collapsible_group' => 'progression_graduation_rules', 'collapsible_group_label' => 'Progression, retakes and graduation rules', 'info' => ['title' => 'When is approval required after attempts?', 'items' => ['State the attempt number or condition that requires approval before another attempt is allowed.']]],
            ['key' => 'retake_after_pass', 'label' => 'Retake after pass', 'type' => 'textarea', 'requirement' => 'O', 'collapsible_group' => 'progression_graduation_rules', 'collapsible_group_label' => 'Progression, retakes and graduation rules', 'info' => ['title' => 'What is the retake-after-pass rule?', 'items' => ['Explain whether a learner who has passed may retake the module and how the new result is treated.']]],
            ['key' => 'retake_mark_cap', 'label' => 'Retake mark cap', 'type' => 'textarea', 'requirement' => 'O', 'collapsible_group' => 'progression_graduation_rules', 'collapsible_group_label' => 'Progression, retakes and graduation rules', 'info' => ['title' => 'What is the retake mark cap?', 'items' => ['Describe the highest mark that may be recorded after a retake, if a cap applies.']]],
            ['key' => 'supplementary_assessment', 'label' => 'Supplementary assessment', 'type' => 'textarea', 'requirement' => 'O', 'collapsible_group' => 'progression_graduation_rules', 'collapsible_group_label' => 'Progression, retakes and graduation rules', 'info' => ['title' => 'What is the supplementary assessment rule?', 'items' => ['Explain who qualifies, when it is offered and how the supplementary result is recorded.']]],
            ['key' => 'maximum_carried_modules', 'label' => 'Maximum carried modules', 'type' => 'text', 'requirement' => 'O', 'collapsible_group' => 'progression_graduation_rules', 'collapsible_group_label' => 'Progression, retakes and graduation rules', 'info' => ['title' => 'What are maximum carried modules?', 'items' => ['Enter the maximum number of failed or incomplete modules a learner may carry while progressing.']]],
            ['key' => 'repeat_gpa_rule', 'label' => 'Repeat effect on GPA', 'type' => 'textarea', 'requirement' => 'O', 'collapsible_group' => 'progression_graduation_rules', 'collapsible_group_label' => 'Progression, retakes and graduation rules', 'info' => ['title' => 'What is the repeat effect on GPA?', 'items' => ['Explain whether the original result, replacement result or both results count when a module is repeated.']]],
            ['key' => 'appeal_override_rules', 'label' => 'Appeals and overrides', 'type' => 'textarea', 'requirement' => 'O', 'min_length' => 20, 'collapsible_group' => 'progression_graduation_rules', 'collapsible_group_label' => 'Progression, retakes and graduation rules', 'info' => ['title' => 'What are appeals and overrides?', 'items' => ['Describe who may appeal or override a progression decision, the approval process and the audit information to retain.']]],
            ['key' => 'graduation_gates', 'label' => 'Graduation gates', 'type' => 'multiselect', 'requirement' => 'O', 'options' => ['core_modules' => 'Compulsory/core modules', 'electives' => 'Electives', 'credits' => 'Credits', 'cgpa' => 'CGPA', 'practicals' => 'Practicals', 'project' => 'Project', 'holds' => 'Holds', 'duration' => 'Maximum duration', 'board_approval' => 'Board approval'], 'min_items' => 1, 'collapsible_group' => 'progression_graduation_rules', 'collapsible_group_label' => 'Progression, retakes and graduation rules', 'info' => ['title' => 'What are graduation gates?', 'items' => ['Select every requirement that must be satisfied before a learner can graduate or receive an award.']]],
            ['key' => 'minimum_graduation_cgpa', 'label' => 'Minimum graduation CGPA', 'type' => 'text', 'requirement' => 'O', 'collapsible_group' => 'progression_graduation_rules', 'collapsible_group_label' => 'Progression, retakes and graduation rules', 'info' => ['title' => 'What is the minimum graduation CGPA?', 'items' => ['Enter the lowest cumulative GPA a learner must achieve to graduate, if applicable.']]],
            ['key' => 'required_graduation_credits', 'label' => 'Required graduation credits', 'type' => 'text', 'requirement' => 'O', 'collapsible_group' => 'progression_graduation_rules', 'collapsible_group_label' => 'Progression, retakes and graduation rules', 'info' => ['title' => 'What are the required graduation credits?', 'items' => ['Enter the total credits a learner must earn before graduation, including any credit rules or exceptions.']]],
            ['key' => 'maximum_completion_duration', 'label' => 'Maximum completion duration', 'type' => 'text', 'requirement' => 'O', 'collapsible_group' => 'progression_graduation_rules', 'collapsible_group_label' => 'Progression, retakes and graduation rules', 'info' => ['title' => 'What is the maximum completion duration?', 'items' => ['Enter the maximum time allowed to complete the programme, such as eight years or sixteen semesters.']]],
            ['key' => 'award_approval_authority', 'label' => 'Award approval authority', 'type' => 'text', 'requirement' => 'O', 'collapsible_group' => 'progression_graduation_rules', 'collapsible_group_label' => 'Progression, retakes and graduation rules', 'info' => ['title' => 'What is the award approval authority?', 'items' => ['Name the body, committee or role that approves final awards and classifications.']]],
            ['key' => 'classification_bands', 'label' => 'Award classifications', 'type' => 'repeatable', 'requirement' => 'O', 'collapsible_group' => 'progression_graduation_rules', 'collapsible_group_label' => 'Progression, retakes and graduation rules', 'info' => ['title' => 'What are award classifications?', 'items' => ['List the award or degree classifications and the CGPA or mark range for each classification.']], 'fields' => [
                ['key' => 'code', 'label' => 'Classification code', 'type' => 'text', 'requirement' => 'R', 'info' => ['title' => 'What is the classification code?', 'items' => ['Enter a short unique code for this classification, such as FIRST or DISTINCTION.']]],
                ['key' => 'label', 'label' => 'Student-facing label', 'type' => 'text', 'requirement' => 'R', 'info' => ['title' => 'What label should students see?', 'items' => ['Enter the official classification wording shown on results and award documents.']]],
                ['key' => 'minimum', 'label' => 'Minimum CGPA/mark', 'type' => 'number', 'requirement' => 'R', 'min' => 0, 'step' => '0.01', 'info' => ['title' => 'What is the minimum CGPA or mark?', 'items' => ['Enter the lowest value at which this classification applies.']]],
                ['key' => 'maximum', 'label' => 'Maximum', 'type' => 'number', 'requirement' => 'R', 'min' => 0, 'step' => '0.01', 'info' => ['title' => 'What is the maximum?', 'items' => ['Enter the highest value included in this classification range.']]],
                ['key' => 'additional_conditions', 'label' => 'Additional conditions', 'type' => 'textarea', 'requirement' => 'O', 'info' => ['title' => 'What are the additional conditions?', 'items' => ['Describe any extra requirements for this classification, such as no failed core modules or board approval.']]],
            ]],
        ],
        'results_lifecycle' => [
            ['key' => 'result_slip_fields', 'label' => 'Result-slip information shown', 'type' => 'multiselect', 'requirement' => 'O', 'collapsible_group' => 'result_slip_details', 'collapsible_group_label' => 'Result-slip details', 'info' => ['title' => 'What should appear on a result slip?', 'items' => ['Select the information normally printed on the official result slip.']], 'options' => ['institution' => 'Institution', 'campus' => 'Campus', 'student' => 'Student', 'programme' => 'Programme', 'modules' => 'Modules', 'marks' => 'Marks', 'grades' => 'Grades', 'gpa' => 'GPA', 'credits' => 'Credits', 'progression' => 'Progression', 'signatures' => 'Signatures', 'security' => 'Security features']],
            ['key' => 'result_slip_layout_requirements', 'label' => 'Result-slip layout and wording', 'type' => 'textarea', 'requirement' => 'O', 'collapsible_group' => 'result_slip_details', 'info' => ['title' => 'What should the result slip look like?', 'items' => ['Describe the layout, wording, signatures and any presentation rules.']]],
            ['key' => 'transcript_fields', 'label' => 'Transcript information shown', 'type' => 'multiselect', 'requirement' => 'O', 'collapsible_group' => 'transcript_details', 'collapsible_group_label' => 'Transcript details', 'info' => ['title' => 'What should appear on a transcript?', 'items' => ['Select the academic history and status information normally printed on the transcript.']], 'options' => ['attempts' => 'Attempts', 'repeats' => 'Repeats', 'transfers' => 'Transfers', 'exemptions' => 'Exemptions', 'gpa' => 'GPA/CGPA', 'credits' => 'Credits', 'classification' => 'Classification', 'award' => 'Award', 'signatures' => 'Signatures', 'security' => 'Security features']],
            ['key' => 'transcript_requirements', 'label' => 'Transcript wording and security', 'type' => 'textarea', 'requirement' => 'O', 'collapsible_group' => 'transcript_details', 'info' => ['title' => 'What transcript rules should we follow?', 'items' => ['Describe wording, verification, signatures, security features and reissue controls.']]],
            ['key' => 'document_availability_rules', 'label' => 'Publication/withholding rules', 'type' => 'textarea', 'requirement' => 'O', 'min_length' => 20, 'collapsible_group' => 'document_lifecycle', 'collapsible_group_label' => 'Document and student lifecycle rules', 'info' => ['title' => 'When may documents be published?', 'items' => ['Explain when result slips or transcripts are released, withheld or restricted.']]],
            ['key' => 'document_retention_reissue_rules', 'label' => 'Correction/reissue/retention rules', 'type' => 'textarea', 'requirement' => 'O', 'min_length' => 20, 'collapsible_group' => 'document_lifecycle', 'info' => ['title' => 'How are corrections and reissues handled?', 'items' => ['Describe retention periods, corrections, versioning and replacement-document controls.']]],
            ['key' => 'applicant_routes', 'label' => 'Applicant routes', 'type' => 'multiselect', 'requirement' => 'O', 'collapsible_group' => 'document_lifecycle', 'info' => ['title' => 'How can applicants enter?', 'items' => ['Select the routes applicants may use to apply or transfer into the institution.']], 'options' => ['online' => 'Online', 'staff_captured' => 'Staff-captured', 'direct' => 'Direct', 'transfer' => 'Transfer', 'rpl' => 'RPL', 'international' => 'International', 'sponsored' => 'Sponsored', 'returning' => 'Returning']],
            ['key' => 'admissions_stages', 'label' => 'Admissions stages/statuses', 'type' => 'textarea', 'requirement' => 'O', 'min_length' => 20, 'collapsible_group' => 'document_lifecycle', 'info' => ['title' => 'Which admissions stages are used?', 'items' => ['List the statuses an applicant moves through from application to admission or rejection.']]],
            ['key' => 'admission_scoring_rules', 'label' => 'Entry scoring/ranking', 'type' => 'textarea', 'requirement' => 'O', 'min_length' => 20, 'collapsible_group' => 'document_lifecycle', 'info' => ['title' => 'How are applicants ranked?', 'items' => ['Describe entry scoring, ranking, tie-breaking or selection rules.']]],
            ['key' => 'student_number_format', 'label' => 'Student number format', 'type' => 'text', 'requirement' => 'O', 'collapsible_group' => 'document_lifecycle', 'info' => ['title' => 'What should a student number look like?', 'items' => ['Provide the pattern or example used when assigning student numbers.']]],
            ['key' => 'applicant_number_format', 'label' => 'Applicant number format', 'type' => 'text', 'requirement' => 'O', 'collapsible_group' => 'document_lifecycle', 'info' => ['title' => 'What should an applicant number look like?', 'items' => ['Provide the pattern or example used when assigning applicant numbers.']]],
            ['key' => 'primary_identity_document', 'label' => 'Primary identity document', 'type' => 'select', 'requirement' => 'O', 'collapsible_group' => 'document_lifecycle', 'info' => ['title' => 'Which identity document is primary?', 'items' => ['Choose the document normally used to verify a student’s identity.']], 'options' => ['national_id' => 'National ID', 'passport' => 'Passport', 'other' => 'Other']],
            ['key' => 'duplicate_detection_rule', 'label' => 'Duplicate detection rule', 'type' => 'textarea', 'requirement' => 'O', 'min_length' => 20, 'collapsible_group' => 'document_lifecycle', 'info' => ['title' => 'How should duplicates be detected?', 'items' => ['Describe the fields and matching rules used to identify possible duplicate people or applications.']]],
            ['key' => 'official_name_order', 'label' => 'Official name order', 'type' => 'text', 'requirement' => 'O', 'collapsible_group' => 'document_lifecycle', 'info' => ['title' => 'How should names be displayed?', 'items' => ['Give the preferred order, such as first name, other names, surname.']]],
            ['key' => 'preferred_date_format', 'label' => 'Preferred date format', 'type' => 'text', 'requirement' => 'O', 'collapsible_group' => 'document_lifecycle', 'info' => ['title' => 'Which date format should be used?', 'items' => ['Provide the format used in screens, reports and official documents.']]],
            ['key' => 'student_lifecycle_statuses', 'label' => 'Student lifecycle statuses', 'type' => 'multiselect', 'requirement' => 'O', 'collapsible_group' => 'document_lifecycle', 'info' => ['title' => 'Which student statuses are needed?', 'items' => ['Select the statuses used from applicant through active study, completion and alumni.']], 'options' => ['applicant' => 'Applicant', 'admitted' => 'Admitted', 'registered' => 'Registered', 'active' => 'Active', 'leave' => 'Leave', 'deferred' => 'Deferred', 'suspended' => 'Suspended', 'withdrawn' => 'Withdrawn', 'discontinued' => 'Discontinued', 'completed' => 'Completed', 'graduated' => 'Graduated', 'alumni' => 'Alumni', 'deceased' => 'Deceased', 'other' => 'Other']],
            ['key' => 'registration_rules', 'label' => 'Registration/module selection rules', 'type' => 'textarea', 'requirement' => 'O', 'min_length' => 20, 'collapsible_group' => 'document_lifecycle', 'info' => ['title' => 'How does registration work?', 'items' => ['Describe registration windows, module selection, approvals and restrictions.']]],
        ],
        'migration' => [
            ['key' => 'migration_scope', 'label' => 'Data to migrate', 'type' => 'multiselect', 'requirement' => 'O', 'options' => ['current_applicants' => 'Current applicants', 'current_students' => 'Current students', 'alumni' => 'Alumni', 'catalogue' => 'Catalogue', 'registrations' => 'Registrations', 'historical_marks' => 'Historical marks', 'gpa' => 'GPA', 'progression' => 'Progression', 'staff' => 'Staff', 'documents' => 'Documents', 'finance' => 'Finance', 'no_migration' => 'No migration']],
        ],
        'integrations_access' => [
            ['key' => 'integration_scope', 'label' => 'Integration needs', 'type' => 'multiselect', 'requirement' => 'O', 'options' => ['email' => 'Email', 'sms' => 'SMS', 'sso' => 'SSO', 'lms' => 'LMS', 'accounting' => 'Accounting', 'payment' => 'Payment', 'regulator' => 'Regulator', 'library' => 'Library', 'biometric' => 'Biometric', 'none' => 'None']],
            ['key' => 'integrations', 'label' => 'Integration register', 'type' => 'repeatable', 'requirement' => 'O', 'fields' => [
                ['key' => 'system_name', 'label' => 'System name', 'type' => 'text', 'requirement' => 'R'],
                ['key' => 'owner', 'label' => 'System owner', 'type' => 'text', 'requirement' => 'R'],
                ['key' => 'purpose', 'label' => 'Purpose', 'type' => 'textarea', 'requirement' => 'R'],
                ['key' => 'method', 'label' => 'Method/API', 'type' => 'text', 'requirement' => 'R'],
                ['key' => 'go_live_priority', 'label' => 'Go-live priority', 'type' => 'select', 'requirement' => 'R', 'options' => ['initial' => 'Initial', 'later' => 'Later', 'discovery_only' => 'Discovery only']],
            ]],
            ['key' => 'user_roles', 'label' => 'User roles and approvals', 'type' => 'repeatable', 'requirement' => 'O', 'fields' => [
                ['key' => 'role', 'label' => 'Role', 'type' => 'text', 'requirement' => 'R'],
                ['key' => 'approximate_users', 'label' => 'Approximate users', 'type' => 'number', 'requirement' => 'O', 'min' => 0, 'step' => 1],
                ['key' => 'permissions', 'label' => 'Key permissions', 'type' => 'textarea', 'requirement' => 'R'],
                ['key' => 'approval_authority', 'label' => 'Approval authority', 'type' => 'text', 'requirement' => 'O'],
                ['key' => 'scope', 'label' => 'Campus/programme scope', 'type' => 'text', 'requirement' => 'O'],
            ]],
            ['key' => 'access_controls', 'label' => 'Access-control requirements', 'type' => 'textarea', 'requirement' => 'O'],
        ],
        'evidence_signoff' => [
            ['key' => 'authorized_representative_name', 'label' => 'Authorized representative name', 'type' => 'text', 'requirement' => 'R'],
            ['key' => 'authorized_representative_position', 'label' => 'Authorized representative position', 'type' => 'text', 'requirement' => 'R'],
            ['key' => 'implementation_lead_name', 'label' => 'Implementation lead confirmation', 'type' => 'text', 'requirement' => 'R'],
            ['key' => 'academic_submission_confirmed', 'label' => 'I confirm that the academic configuration is complete and may be submitted for review.', 'type' => 'boolean', 'requirement' => 'R', 'must_be_true' => true],
            ['key' => 'attachments', 'label' => 'Attachment register', 'type' => 'repeatable', 'requirement' => 'O', 'fields' => [
                ['key' => 'type', 'label' => 'Attachment type', 'type' => 'text', 'requirement' => 'R'],
                ['key' => 'requirement', 'label' => 'Requirement level', 'type' => 'select', 'requirement' => 'R', 'options' => ['required' => 'Required', 'optional' => 'Optional', 'if_migrating' => 'If migrating', 'if_applicable' => 'If applicable']],
                ['key' => 'file_name', 'label' => 'File name/version note', 'type' => 'text', 'requirement' => 'O'],
                ['key' => 'notes', 'label' => 'Notes/owner', 'type' => 'text', 'requirement' => 'O'],
            ]],
            ['key' => 'open_decisions', 'label' => 'Open decisions and assumptions', 'type' => 'repeatable', 'requirement' => 'O', 'fields' => [
                ['key' => 'decision', 'label' => 'Decision/assumption', 'type' => 'textarea', 'requirement' => 'R'],
                ['key' => 'owner', 'label' => 'Owner', 'type' => 'text', 'requirement' => 'R'],
                ['key' => 'due_date', 'label' => 'Due date', 'type' => 'date', 'requirement' => 'O'],
                ['key' => 'status', 'label' => 'Status', 'type' => 'select', 'requirement' => 'R', 'options' => ['open' => 'Open', 'agreed' => 'Agreed', 'deferred' => 'Deferred', 'closed' => 'Closed']],
            ]],
        ],
    ],
];
