<?php

return [
    'schema_version' => '1.0',
    'invitation_expires_days' => (int) env('CLIENT_SETUP_INVITATION_EXPIRES_DAYS', 30),
    'verification_code_expires_minutes' => (int) env('CLIENT_SETUP_VERIFICATION_CODE_EXPIRES_MINUTES', 10),
    'verification_code_resend_cooldown_seconds' => (int) env('CLIENT_SETUP_VERIFICATION_CODE_RESEND_COOLDOWN_SECONDS', 60),
    'verification_max_attempts' => (int) env('CLIENT_SETUP_VERIFICATION_MAX_ATTEMPTS', 5),
    'invitation_url_route' => 'client-setup.entry',
    'session_verified_invitation_key' => 'client_setup_verified_invitation_uuid',
    'stage_key_pattern' => '/^[a-z0-9][a-z0-9_-]{0,79}$/',
    'stage_statuses' => [
        'not_started',
        'in_progress',
        'complete',
    ],
    'required_stage_attachments' => [
        'results_lifecycle' => ['Result slip', 'Transcript'],
    ],
    'template_version' => '1.0',
    'migration_upload_max_kb' => 20480,
    'release' => [
        'scanner_adapter' => env('CLIENT_SETUP_SCANNER_ADAPTER'),
        'importer_adapter' => env('CLIENT_SETUP_IMPORTER_ADAPTER'),
        'backup_verified' => (bool) env('CLIENT_SETUP_BACKUP_VERIFIED', false),
        'pilot_approved' => (bool) env('CLIENT_SETUP_PILOT_APPROVED', false),
        'required_tables' => [
            'crm_client_setup_submissions',
            'crm_client_setup_invitations',
            'crm_client_setup_stage_progress',
            'crm_client_setup_revisions',
            'crm_client_setup_events',
            'crm_client_setup_attachments',
            'crm_client_setup_migration_uploads',
            'crm_client_setup_notifications',
        ],
    ],
    'notifications' => [
        'enabled' => (bool) env('CLIENT_SETUP_NOTIFICATIONS_ENABLED', true),
        'mail_retry_attempts' => (int) env('CLIENT_SETUP_MAIL_RETRY_ATTEMPTS', 3),
        'crm_fallback_roles' => ['admin', 'manager'],
        'reminders' => [
            'enabled' => (bool) env('CLIENT_SETUP_REMINDERS_ENABLED', true),
            'draft_after_hours' => (int) env('CLIENT_SETUP_DRAFT_REMINDER_AFTER_HOURS', 72),
            'submitted_after_hours' => (int) env('CLIENT_SETUP_SUBMITTED_REMINDER_AFTER_HOURS', 48),
            'repeat_after_hours' => (int) env('CLIENT_SETUP_REMINDER_REPEAT_AFTER_HOURS', 72),
            'expiry_warning_hours' => (int) env('CLIENT_SETUP_EXPIRY_WARNING_HOURS', 72),
        ],
    ],
    'migration_templates' => [
        'staff' => [
            'label' => 'Staff',
            'filename' => 'heritage-client-setup-staff-template-v1.0.xlsx',
            'path' => 'client_setup_templates/v1.0/heritage-client-setup-staff-template-v1.0.xlsx',
            'headings' => ['firstname', 'middlename', 'lastname', 'email', 'date_of_birth', 'gender', 'position', 'phone', 'id_number', 'nationality', 'city', 'address', 'active', 'status', 'department_name', 'roles', 'reporting_to_email', 'start_year', 'username'],
            'required' => ['firstname', 'lastname', 'email', 'date_of_birth', 'gender', 'active', 'status'],
            'allowed' => [
                'gender' => ['M', 'F'],
                'active' => ['Yes', 'No'],
                'status' => ['Current', 'Inactive'],
            ],
        ],
        'students' => [
            'label' => 'Students',
            'filename' => 'heritage-client-setup-student-template-v1.0.xlsx',
            'path' => 'client_setup_templates/v1.0/heritage-client-setup-student-template-v1.0.xlsx',
            'headings' => ['first_name', 'last_name', 'other_names', 'student_number', 'gender', 'date_of_birth', 'nationality', 'id_number', 'email', 'phone', 'status', 'program_code', 'level', 'next_of_kin_name', 'next_of_kin_email', 'next_of_kin_phone'],
            'required' => ['first_name', 'last_name', 'student_number', 'gender', 'date_of_birth', 'status', 'program_code', 'level'],
            'allowed' => [
                'gender' => ['M', 'F'],
                'status' => ['active', 'inactive', 'completed', 'withdrawn'],
            ],
        ],
    ],
    'migration_template_compatibility' => [
        'staff' => [
            'allow_legacy' => false,
            'versions' => [
                '1.0' => [
                    'headings' => ['firstname', 'middlename', 'lastname', 'email', 'date_of_birth', 'gender', 'position', 'phone', 'id_number', 'nationality', 'city', 'address', 'active', 'status', 'department_name', 'roles', 'reporting_to_email', 'start_year', 'username'],
                ],
            ],
        ],
        'students' => [
            'allow_legacy' => false,
            'versions' => [
                '1.0' => [
                    'headings' => ['first_name', 'last_name', 'other_names', 'student_number', 'gender', 'date_of_birth', 'nationality', 'id_number', 'email', 'phone', 'status', 'program_code', 'level', 'next_of_kin_name', 'next_of_kin_email', 'next_of_kin_phone'],
                ],
            ],
        ],
    ],
    'stages' => [
        [
            'key' => 'scope',
            'number' => 0,
            'label' => 'Welcome and scope',
            'short_label' => 'Scope',
            'description' => 'Confirm the institution, implementation scope and the people responsible for this submission.',
            'required_for_academic' => true,
            'optional' => false,
            'help' => [
                'Confirm the legal institution name and implementation scope.',
                'Use Save and continue when this stage is ready for review.',
            ],
        ],
        [
            'key' => 'institution',
            'number' => 1,
            'label' => 'Institution and academic foundation',
            'short_label' => 'Institution',
            'description' => 'Describe the institution, campuses, academic structure, calendar and responsible contacts.',
            'required_for_academic' => true,
            'optional' => false,
            'help' => [
                'Add the academic structure used by the institution.',
                'Include campus and contact details where they differ by scope.',
            ],
        ],
        [
            'key' => 'programmes',
            'number' => 2,
            'label' => 'Programme portfolio',
            'short_label' => 'Programmes',
            'description' => 'Register the active programmes, awards, levels, delivery modes and entry requirements.',
            'required_for_academic' => true,
            'optional' => false,
            'help' => [
                'Add each active programme as a separate row.',
                'Programme codes should remain stable for later imports and integrations.',
            ],
        ],
        [
            'key' => 'curriculum',
            'number' => 3,
            'label' => 'Curriculum and modules',
            'short_label' => 'Curriculum',
            'description' => 'Capture curriculum versions, module structures, credits, electives and practical requirements.',
            'required_for_academic' => true,
            'optional' => false,
            'help' => [
                'State clearly if curriculum configuration is in scope for the first release.',
                'Keep module codes unique within each curriculum version.',
            ],
        ],
        [
            'key' => 'assessment',
            'number' => 4,
            'label' => 'Assessment, grading and GPA',
            'short_label' => 'Assessment',
            'description' => 'Define assessment components, grading scales, GPA rules and official result approval.',
            'required_for_academic' => true,
            'optional' => false,
            'help' => [
                'List every assessment component used in the selected academic scope.',
                'Assessment weights must reconcile to the institution’s approved rules.',
            ],
        ],
        [
            'key' => 'progression',
            'number' => 5,
            'label' => 'Progression, retakes and graduation',
            'short_label' => 'Progression',
            'description' => 'Explain progression decisions, supplementary assessments, retakes, classifications and graduation rules.',
            'required_for_academic' => true,
            'optional' => false,
            'help' => [
                'Describe the conditions that permit or prevent progression.',
                'Include the approval action and student-facing label for each rule.',
            ],
        ],
        [
            'key' => 'results_lifecycle',
            'number' => 6,
            'label' => 'Results, transcripts and student lifecycle',
            'short_label' => 'Results and lifecycle',
            'description' => 'Define result slips, transcripts, publication rules and the student lifecycle information required.',
            'required_for_academic' => true,
            'optional' => false,
            'help' => [
                'List the information that must appear on official result documents.',
                'Describe holds, corrections, approvals and verification requirements.',
                'Upload a current result slip and transcript example before completing this stage.',
            ],
        ],
        [
            'key' => 'migration',
            'number' => 7,
            'label' => 'Migration and data readiness',
            'short_label' => 'Migration',
            'description' => 'Record datasets, source systems, data owners and the readiness of staff and student imports.',
            'required_for_academic' => false,
            'optional' => true,
            'help' => [
                'Select no migration when the implementation starts without historical data.',
                'Use the supplied staff and student templates for staged migration planning.',
            ],
        ],
        [
            'key' => 'integrations_access',
            'number' => 8,
            'label' => 'Integrations, users and access',
            'short_label' => 'Integrations and access',
            'description' => 'Record integration needs, user roles, approval authorities and access-control requirements.',
            'required_for_academic' => false,
            'optional' => true,
            'help' => [
                'List integrations that are agreed for discovery or delivery.',
                'Describe access controls without blocking academic submission.',
            ],
        ],
        [
            'key' => 'evidence_signoff',
            'number' => 9,
            'label' => 'Evidence and sign-off',
            'short_label' => 'Evidence and sign-off',
            'description' => 'Attach supporting evidence, confirm the submission and record final implementation conditions.',
            'required_for_academic' => true,
            'optional' => false,
            'help' => [
                'Attach evidence only where the selected scope requires it.',
                'The authorized representative confirmation is required before final completion.',
            ],
        ],
    ],
];
