<?php

return [
    'meta' => [
        'default_title' => 'Heritage Pro — Intelligent school management for Africa',
    ],
    'nav' => [
        ['label' => 'Products', 'route' => 'website.products'],
        ['label' => 'Features', 'route' => 'website.features'],
        ['label' => 'Customers', 'route' => 'website.customers'],
        ['label' => 'Pricing', 'route' => 'website.pricing'],
        ['label' => 'About', 'route' => 'website.about'],
        ['label' => 'Team', 'route' => 'website.team'],
        ['label' => 'FAQ', 'route' => 'website.faq'],
    ],
    'pages' => [
        'home' => [
            'title' => 'Heritage Pro — Intelligent school management for Africa',
            'hero' => [
                'eyebrow' => 'Built in Botswana · Trusted across Southern Africa',
                'title' => 'The intelligent operating system for every school, college, and institution.',
                'lead' => 'Heritage Pro unifies admissions, academics, attendance, fees, communications, and reporting on a single, secure platform — built for K-12, secondary schools, and tertiary institutions.',
                'secondary_label' => 'See the product',
                'secondary_href' => '#features',
                'show_play_icon' => true,
            ],
        ],
        'products' => [
            'title' => 'Heritage Pro — Product Editions',
            'hero' => [
                'eyebrow' => 'Product editions',
                'title' => 'Purpose-built systems for junior schools, senior schools, and colleges.',
                'lead' => 'Choose the Heritage Pro deployment that fits your institution: junior school operations, senior school academic management, or collegiate and Institute of Health Sciences administration.',
                'secondary_label' => 'Compare features',
                'secondary_route' => 'website.features',
            ],
        ],
        'features' => [
            'title' => 'Heritage Pro — Features',
            'hero' => [
                'eyebrow' => 'Platform capabilities',
                'title' => 'Modules that connect academics, administration, and learning.',
                'lead' => 'Heritage Pro combines admissions, academic management, attendance, assessment, communication, fees, learning, library, HR, and analytics in one secure operating system.',
                'secondary_label' => 'See products',
                'secondary_route' => 'website.products',
            ],
        ],
        'customers' => [
            'title' => 'Heritage Pro — Customers',
            'hero' => [
                'eyebrow' => 'Selected live clients',
                'title' => 'Selected live institutions running Heritage Pro.',
                'lead' => 'A few of the junior schools, senior schools, and college deployments currently live on Heritage Pro across Botswana.',
                'secondary_label' => 'About Heritage Pro',
                'secondary_route' => 'website.about',
            ],
        ],
        'pricing' => [
            'title' => 'Heritage Pro — Pricing',
            'hero' => [
                'eyebrow' => 'Pricing and rollout',
                'title' => 'Flexible pricing for school and tertiary deployments.',
                'lead' => 'Heritage Pro supports small schools, senior schools, and larger tertiary institutions with pricing designed around learner volume and institutional scope.',
                'secondary_label' => 'See features',
                'secondary_route' => 'website.features',
            ],
        ],
        'about' => [
            'title' => 'Heritage Pro — About',
            'hero' => [
                'eyebrow' => 'About Heritage Pro',
                'title' => 'Built in Botswana for institutions that need one reliable operating system.',
                'lead' => 'Heritage Pro brings admissions, academics, attendance, assessments, learning, communication, fees, documents, HR, and reporting into one connected environment for junior schools, senior schools, and colleges.',
                'secondary_label' => 'View products',
                'secondary_route' => 'website.products',
            ],
        ],
        'faq' => [
            'title' => 'Heritage Pro — FAQ',
            'hero' => [
                'eyebrow' => 'Frequently asked',
                'title' => 'Answers to the questions institutions ask most often.',
                'lead' => 'From migrations and hosting to security, messaging, and rollout support, Heritage Pro is built to be practical for real schools and tertiary institutions.',
                'secondary_label' => 'About Heritage Pro',
                'secondary_route' => 'website.about',
            ],
        ],
        'team' => [
            'title' => 'Heritage Pro — Team',
            'hero' => [
                'eyebrow' => 'Meet the team',
                'title' => 'The people building, running, and supporting Heritage Pro.',
                'lead' => 'A compact team focused on product direction, delivery operations, and day-to-day platform development for institutions across Botswana and Southern Africa.',
                'secondary_label' => 'Book a demo',
                'secondary_href' => '#contact',
            ],
        ],
    ],
    'hero_trust' => [
        ['value' => '98+', 'label' => 'institutions'],
        ['value' => '84,000+', 'label' => 'learners'],
        ['value' => '99.95%', 'label' => 'uptime'],
    ],
    'stats' => [
        ['value' => '98+', 'label' => 'Institutions running Heritage Pro'],
        ['value' => '84,000+', 'label' => 'Learners with live records'],
        ['value' => '99.95%', 'label' => 'Platform uptime, measured monthly'],
        ['value' => '12×', 'label' => 'Faster report-card turnaround'],
    ],
    'hero_dashboard' => [
        'stats' => [
            ['value' => '1,248', 'label' => 'Active students', 'badge' => '+34'],
            ['value' => '96.4%', 'label' => 'Attendance', 'badge' => '+1.2%'],
            ['value' => 'BWP 412k', 'label' => 'Fees collected', 'badge' => '78%'],
        ],
        'rows' => [
            ['name' => 'Boitumelo Mosadi', 'code' => '3R', 'status' => 'Paid', 'theme' => 'ok'],
            ['name' => 'Atang Nkhata', 'code' => '1S', 'status' => 'Due', 'theme' => 'warn'],
            ['name' => 'Lesedi Moeti', 'code' => '2R', 'status' => 'Paid', 'theme' => 'ok'],
            ['name' => 'Kago Tshekiso', 'code' => '4A', 'status' => 'Overdue', 'theme' => 'danger'],
        ],
        'bars' => [42, 58, 48, 64, 70, 66, 78, 84, 80, 92, 98, 110],
    ],
    'sidebar_modules' => [
        ['label' => 'Dashboard', 'active' => true],
        ['label' => 'Students', 'active' => false],
        ['label' => 'Attendance', 'active' => false],
        ['label' => 'Academics Manager', 'active' => false],
        ['label' => 'Invigilation Roster', 'active' => false],
        ['label' => 'Scheme of Work', 'active' => false],
        ['label' => 'Learning Space', 'active' => false],
        ['label' => 'Timetable', 'active' => false],
        ['label' => 'Assessments', 'active' => false],
        ['label' => 'Human Resources', 'active' => false],
        ['label' => 'Fees Administration', 'active' => false],
    ],
    'clients' => [
        ['mark' => 'BJ', 'label' => 'Baitirile Junior School', 'type' => 'Junior school deployment'],
        ['mark' => 'BJ', 'label' => 'Bakgatle Junior School', 'type' => 'Junior school deployment'],
        ['mark' => 'GJ', 'label' => 'Gaborone Junior School', 'type' => 'Junior school deployment'],
        ['mark' => 'FS', 'label' => 'Francistown Senior School', 'type' => 'Senior school deployment'],
        ['mark' => 'S', 'label' => 'Sunnysands', 'type' => 'Senior school deployment'],
        ['mark' => 'IO', 'label' => 'Institute of Health Sciences', 'type' => 'College / IHS deployment'],
    ],
    'products' => [
        [
            'theme' => 'schools',
            'badge' => 'Junior Schools',
            'icon' => 'book',
            'title' => 'Heritage Pro — Junior Schools',
            'description' => 'For junior schools managing admissions, sponsors or parent records, student records, attendance, assessment, communications, fees administration, and houses or teams.',
            'items' => [
                'Admissions and sponsor or parent records',
                'Student records, attendance, and health history',
                'Assessment workflows and report cards',
                'Fees administration, communications, and houses',
            ],
            'cta' => 'View features',
            'route' => 'website.features',
        ],
        [
            'theme' => 'k12',
            'badge' => 'Senior Schools',
            'icon' => 'child',
            'title' => 'Heritage Pro — Senior Schools',
            'description' => 'For senior schools that need stronger academic control across classes, teacher allocation, assessments, attendance, report cards, communication, and financial administration.',
            'items' => [
                'Academic management and class organisation',
                'Assessment capture, analysis, and reporting',
                'Attendance, communication, and HR records',
                'Fees administration and performance visibility',
            ],
            'cta' => 'Explore pricing',
            'route' => 'website.pricing',
        ],
        [
            'theme' => 'collegiate',
            'badge' => 'College / IHS',
            'icon' => 'grad',
            'title' => 'Heritage Pro — Collegiate & IHS',
            'description' => 'For colleges and Institute of Health Sciences deployments handling admissions, student lifecycle management, semesters, LMS delivery, online assessments, transcripts, attendance, library, HR, and sponsorships.',
            'items' => [
                'Admissions, registration, and module enrollment',
                'Semester control, grading, and transcripts',
                'Learning management, assignments, and tests',
                'Attendance, library, HR, sponsorships, and analytics',
            ],
            'cta' => 'Learn more',
            'route' => 'website.about',
        ],
    ],
    'feature_rows' => [
        [
            'eyebrow' => 'School management',
            'title' => 'Run admissions, student records, attendance, and academic administration from one place.',
            'description' => 'Heritage Pro supports online applications, sponsor and parent records, student profiles, attendance tracking, class management, subject allocation, and institution-wide academic oversight in a connected workflow.',
            'items' => [
                '<b>Admissions workflow</b> — applications, document capture, and enrollment processing.',
                '<b>Student records</b> — health, behaviour, transfer history, and examination access.',
                '<b>Academic management</b> — classes, teacher assignments, optional subjects, and grading matrices.',
                '<b>Attendance control</b> — daily capture aligned to official attendance requirements.',
            ],
            'cta' => 'See products',
            'route' => 'website.products',
        ],
        [
            'eyebrow' => 'Assessment and reporting',
            'title' => 'Capture scores, automate report cards, and publish results with less manual work.',
            'description' => 'From continuous assessment and examination marks to automated comments, value-addition analysis, report-card generation, and parent-facing delivery, Heritage Pro simplifies the reporting cycle for school leaders and teachers.',
            'items' => [
                '<b>Assessment capture</b> — coursework, examinations, and detailed score analysis.',
                '<b>Report cards</b> — creation, archiving, and communication-ready publishing.',
                '<b>Communications</b> — notices, SMS, email, and bulk report-card distribution.',
                '<b>Fees administration</b> — charges, receipts, statements, and payment analysis.',
            ],
            'cta' => 'View pricing',
            'route' => 'website.pricing',
        ],
        [
            'eyebrow' => 'College and IHS operations',
            'title' => 'Manage higher education administration, digital learning, and academic records end to end.',
            'description' => 'The collegiate deployment centralises admissions, academic structures, semesters, module enrollment, LMS delivery, online assessments, transcripts, attendance, document workflows, library operations, HR, assets, sponsorships, and alumni.',
            'items' => [
                '<b>Student lifecycle</b> — application, admission, registration, progression, graduation, and alumni.',
                '<b>Academic structure</b> — faculties, departments, programmes, modules, offerings, and lecturer assignments.',
                '<b>Digital learning</b> — LMS content, tests, assignments, discussion forums, and progress tracking.',
                '<b>Institution services</b> — documents, library, HR, assets, sponsorships, and analytics.',
            ],
            'cta' => 'About Heritage Pro',
            'route' => 'website.about',
        ],
    ],
    'modules' => [
        ['icon' => 'shield', 'title' => 'Core Platform & Authentication', 'description' => 'Secure login, role-based access, permissions, session control, and audit-ready platform foundations.'],
        ['icon' => 'cpu', 'title' => 'Dashboard & Analytics', 'description' => 'Institution dashboards, operational metrics, academic insights, and at-risk visibility.'],
        ['icon' => 'users', 'title' => 'Student Management', 'description' => 'Student profiles, transfers, guardians, health records, histories, and lifecycle tracking.'],
        ['icon' => 'clipboard', 'title' => 'Admissions Module', 'description' => 'Online applications, screening, document capture, selection, enrollment, and placement workflows.'],
        ['icon' => 'book', 'title' => 'Academic Structure Management', 'description' => 'Grades, classes, subjects, departments, programmes, teacher allocation, and academic setup.'],
        ['icon' => 'bio', 'title' => 'Assessment Engine (Multi-School Type)', 'description' => 'Assessment capture and grading across junior, senior, primary, reception, and college workflows.'],
        ['icon' => 'grad', 'title' => 'Finals & Graduation Module', 'description' => 'Final examination analysis, graduation readiness, progression, awards, and result publishing.'],
        ['icon' => 'calendar', 'title' => 'Activities and Events Module', 'description' => 'Activities, event calendars, rosters, eligibility checks, attendance, and results tracking.'],
        ['icon' => 'credit', 'title' => 'Fee Management System', 'description' => 'Charges, invoices, receipts, discounts, refunds, statements, and payment analysis.'],
        ['icon' => 'calendar', 'title' => 'Attendance Module (Students)', 'description' => 'Daily student registers, attendance codes, summaries, and compliance-ready reporting.'],
        ['icon' => 'bio', 'title' => 'Staff Attendance & Biometric Integration', 'description' => 'Staff shifts, biometric device sync, corrections, holiday rules, and monthly exports.'],
        ['icon' => 'calendar', 'title' => 'Timetable Generation Engine', 'description' => 'Timetable constraints, room allocation, teacher schedules, generation, and conflict checks.'],
        ['icon' => 'lib', 'title' => 'Library Management System', 'description' => 'Catalogues, borrowers, loans, reservations, inventory, fines, and library reporting.'],
        ['icon' => 'book', 'title' => 'Learning Management System (LMS)', 'description' => 'Learning content, assignments, online tests, discussion forums, and progress tracking.'],
        ['icon' => 'grad', 'title' => 'Staff Personal Development Plans (PDP)', 'description' => 'PDP templates, targets, reviews, evidence, progress tracking, and staff development records.'],
        ['icon' => 'clipboard', 'title' => 'Schemes of Work & Lesson Planning', 'description' => 'Scheme planning, lesson plans, curriculum pacing, approvals, and teaching coverage visibility.'],
        ['icon' => 'calendar', 'title' => 'Leave Management System', 'description' => 'Leave types, balances, requests, approvals, statements, and policy-based staff leave control.'],
        ['icon' => 'users', 'title' => 'Student Welfare & Counseling', 'description' => 'Health incidents, support records, communications, interventions, and welfare follow-up.'],
        ['icon' => 'clipboard', 'title' => 'Document Management System', 'description' => 'Institutional documents, sharing, approvals, expiry tracking, audit logs, and secure storage.'],
        ['icon' => 'megaphone', 'title' => 'Communications Engine (SMS, Email, WhatsApp)', 'description' => 'Messaging templates, campaigns, bulk communication, delivery tracking, and targeted outreach.'],
        ['icon' => 'megaphone', 'title' => 'Notification System', 'description' => 'In-app alerts, reminders, status updates, system notifications, and user-facing activity prompts.'],
        ['icon' => 'users', 'title' => 'Contact & Sponsor Management', 'description' => 'Contacts, guardians, sponsors, sponsor-student links, communication records, and billing context.'],
        ['icon' => 'bus', 'title' => 'Asset Management', 'description' => 'Asset registers, assignments, audits, maintenance, disposals, and institutional inventory control.'],
        ['icon' => 'grad', 'title' => 'House Management & Analysis', 'description' => 'House allocation, awards, performance analysis, student grouping, and team visibility.'],
        ['icon' => 'cpu', 'title' => 'Reporting & Data Export Engine', 'description' => 'PDF and Excel exports, report cards, institutional summaries, analytics, and custom reporting.'],
        ['icon' => 'shield', 'title' => 'System Administration & Settings', 'description' => 'School setup, terms, grades, thresholds, integrations, permissions, and platform configuration.'],
        ['icon' => 'cpu', 'title' => 'Multi-School Mode Provisioning', 'description' => 'Different school configurations, product modes, and deployment settings from one platform foundation.'],
        ['icon' => 'users', 'title' => 'Student & Sponsor Portals', 'description' => 'Portal access for students and sponsors with records, notices, documents, and account visibility.'],
        ['icon' => 'mail', 'title' => 'Staff Direct Messaging', 'description' => 'In-app staff messaging, discussion threads, attachments, mentions, and internal communication.'],
        ['icon' => 'calendar', 'title' => 'Invigilation Roster', 'description' => 'Exam invigilator scheduling, venue planning, staff allocation, and readiness coordination.'],
    ],
    'deployment_highlights' => [
        [
            'avatar' => 'BJ',
            'title' => 'Baitirile Junior School',
            'subtitle' => 'Junior schools deployment',
            'body' => 'Live on Heritage Pro for admissions, student records, attendance, assessments, communications, fees administration, and house or team workflows.',
        ],
        [
            'avatar' => 'FS',
            'title' => 'Francistown Senior School',
            'subtitle' => 'Senior schools deployment',
            'body' => 'Live on Heritage Pro for academic management, attendance, report cards, assessment capture, communication, and operational oversight.',
        ],
        [
            'avatar' => 'IO',
            'title' => 'Institute of Health Sciences',
            'subtitle' => 'College / IHS deployment',
            'body' => 'Live on Heritage Pro collegiate workflows for admissions, semester registration, LMS delivery, online assessments, transcripts, and attendance.',
        ],
    ],
    'customer_cards' => [
        [
            'theme' => 'schools',
            'tag' => 'Junior Schools',
            'kicker' => 'Baitirile · Bakgatle · Gaborone',
            'title' => 'Daily school operations running in one flow.',
            'description' => 'Selected junior school deployments are live on Heritage Pro for admissions, attendance, assessments, communications, and fees administration.',
            'metrics' => [
                ['value' => 'Admissions', 'label' => 'Live focus'],
                ['value' => 'Attendance', 'label' => 'Operational flow'],
            ],
        ],
        [
            'theme' => 'k12',
            'tag' => 'Senior Schools',
            'kicker' => 'Francistown Senior · Sunnysands',
            'title' => 'Academic control for full term cycles.',
            'description' => 'Senior school deployments are using Heritage Pro for timetable visibility, assessments, intervention tracking, report publishing, and school-wide administration.',
            'metrics' => [
                ['value' => 'Assessments', 'label' => 'Live focus'],
                ['value' => 'Timetable', 'label' => 'Operational flow'],
            ],
        ],
        [
            'theme' => 'collegiate',
            'tag' => 'College / IHS',
            'kicker' => 'Institute of Health Sciences',
            'title' => 'Collegiate administration with learning built in.',
            'description' => 'The IHS deployment runs registration, learning delivery, online assessments, transcripts, attendance, sponsorship handling, and academic reporting in one platform.',
            'metrics' => [
                ['value' => 'Learning Space', 'label' => 'Live focus'],
                ['value' => 'Transcripts', 'label' => 'Operational flow'],
            ],
        ],
    ],
    'team_members' => [
        [
            'name' => 'Chief Executive Officer',
            'short_name' => 'CEO',
            'role' => 'Leadership & product direction',
            'bio' => 'Leads product vision, institutional partnerships, and the long-term direction of Heritage Pro across schools and tertiary environments.',
            'focus' => ['Strategy', 'Product leadership', 'Partnerships'],
            'theme' => 'lead',
        ],
        [
            'name' => 'Operations Manager',
            'short_name' => 'OM',
            'role' => 'Delivery & client operations',
            'bio' => 'Coordinates onboarding, rollout planning, client support, and operational follow-through so deployments stay reliable after go-live.',
            'focus' => ['Onboarding', 'Client operations', 'Support delivery'],
            'theme' => 'ops',
        ],
        [
            'name' => 'Lead Developer',
            'short_name' => 'LD',
            'role' => 'Platform architecture',
            'bio' => 'Owns core platform engineering, system design, and the technical direction behind Heritage Pro’s school and collegiate modules.',
            'focus' => ['Architecture', 'Core platform', 'Security'],
            'theme' => 'dev',
        ],
        [
            'name' => 'Backend Developer',
            'short_name' => 'BD',
            'role' => 'Workflows & integrations',
            'bio' => 'Builds the academic, operational, and reporting workflows that connect admissions, assessments, attendance, fees, and learning.',
            'focus' => ['Backend systems', 'Integrations', 'Reporting'],
            'theme' => 'dev',
        ],
        [
            'name' => 'Frontend Developer',
            'short_name' => 'FD',
            'role' => 'User experience & interfaces',
            'bio' => 'Shapes the public website, dashboards, and product interfaces so staff, students, and institutions can move through the platform clearly.',
            'focus' => ['Frontend', 'UX', 'Interface systems'],
            'theme' => 'dev',
        ],
    ],
    'pricing_cards' => [
        [
            'name' => 'Starter',
            'amount' => 'BWP 28',
            'unit' => 'per learner / month',
            'description' => 'For schools up to 500 learners starting with core admissions, academics, and fees.',
            'items' => [
                'Student records & admissions',
                'Report cards & attendance',
                'Fees & invoicing',
                '500 SMS / month included',
                'Email & chat support',
            ],
            'cta' => 'Choose Starter',
            'href' => '#contact',
            'highlight' => false,
        ],
        [
            'name' => 'Professional',
            'amount' => 'BWP 42',
            'unit' => 'per learner / month',
            'description' => 'For established schools that need advanced workflows, parent comms, and analytics.',
            'items' => [
                'Everything in Starter',
                'Parent portal & WhatsApp',
                'Library, transport & health',
                'Analytics & board dashboards',
                'Priority support + named CSM',
            ],
            'cta' => 'Choose Professional',
            'href' => '#contact',
            'highlight' => true,
            'ribbon' => 'Most popular',
        ],
        [
            'name' => 'Institution',
            'amount' => 'Custom',
            'unit' => 'for colleges & groups',
            'description' => 'For tertiary institutions and multi-campus groups with sponsor billing and SSO.',
            'items' => [
                'Everything in Professional',
                'Heritage Pro Collegiate edition',
                'DTEF / sponsor billing',
                'SAML SSO & custom roles',
                'Dedicated onboarding team',
            ],
            'cta' => 'Talk to sales',
            'href' => '#contact',
            'highlight' => false,
        ],
    ],
    'faq_items' => [
        [
            'question' => 'Is Heritage Pro compliant with Botswana Ministry of Education reporting?',
            'answer' => 'Yes. Heritage Pro generates BEC, MoESD, and Ministry-format returns out of the box. BGCSE, JCE, and PSLE workflows are certified and updated each academic year.',
        ],
        [
            'question' => 'Can we migrate data from our old system?',
            'answer' => 'Absolutely. Our onboarding team handles CSV, Excel, and SQL migrations from most common SIS platforms at no extra cost during the first 60 days.',
        ],
        [
            'question' => 'How does WhatsApp / SMS pricing work?',
            'answer' => 'Every plan includes a monthly SMS and WhatsApp allowance. Additional messages are billed at cost — typically BWP 0.18 per SMS and BWP 0.09 per WhatsApp message, with no markup.',
        ],
        [
            'question' => 'Where is our data stored?',
            'answer' => 'Student data is stored in AWS af-south-1 (Cape Town), with nightly off-site backups and optional on-premise mirror for government institutions. All data remains within SADC.',
        ],
        [
            'question' => 'Do parents need an app?',
            'answer' => 'No. Parents receive reports and notices over WhatsApp and SMS by default. A mobile-responsive parent portal is available but optional.',
        ],
        [
            'question' => 'What happens if we cancel?',
            'answer' => 'Your data is yours. We export everything to CSV and PDF and retain a read-only archive for 90 days. No lock-in, no penalties.',
        ],
    ],
    'blog_articles' => [
        [
            'cover' => 'a',
            'tag' => 'Playbook',
            'title' => 'Cutting report-card turnaround from 3 weeks to 48 hours',
            'description' => 'A step-by-step operating rhythm for heads of department, based on a senior school reporting cycle.',
            'meta' => '8 min read · Apr 2025',
        ],
        [
            'cover' => 'b',
            'tag' => 'Policy',
            'title' => 'What the new BGCSE reporting rubric means for 2025',
            'description' => 'A plain-English guide to the Ministry\'s rubric refresh, and how to re-weight your assessment calendar.',
            'meta' => '6 min read · Mar 2025',
        ],
        [
            'cover' => 'c',
            'tag' => 'Product',
            'title' => 'How sponsor billing should work — DTEF, done right',
            'description' => 'Why a fee ledger built for individual payers falls over when 60% of tuition is sponsor-funded.',
            'meta' => '7 min read · Feb 2025',
        ],
    ],
    'contact' => [
        'eyebrow' => 'Get started',
        'title' => 'Book a 30-minute demo.',
        'description' => 'See Heritage Pro on your own data. Our team will tailor the walkthrough to your school, import a sample of your records, and answer every question.',
        'details' => [
            ['icon' => 'pin', 'label' => 'Head office', 'value' => 'Plot 50371, CBD · Gaborone, Botswana'],
            ['icon' => 'mail', 'label' => 'Email', 'value' => 'hello@heritagepro.co'],
            ['icon' => 'phone', 'label' => 'Phone', 'value' => '+267 390 5400'],
        ],
    ],
    'footer' => [
        'description' => 'The intelligent operating system for schools, colleges, and institutions across Southern Africa.',
        'social' => [
            ['icon' => 'linkedin', 'label' => 'LinkedIn', 'href' => '#'],
            ['icon' => 'twitter', 'label' => 'Twitter', 'href' => '#'],
            ['icon' => 'facebook', 'label' => 'Facebook', 'href' => '#'],
            ['icon' => 'yt', 'label' => 'YouTube', 'href' => '#'],
        ],
        'columns' => [
            [
                'title' => 'Products',
                'links' => [
                    ['label' => 'Junior Schools', 'route' => 'website.products'],
                    ['label' => 'Senior Schools', 'route' => 'website.products'],
                    ['label' => 'Collegiate', 'route' => 'website.products'],
                    ['label' => 'Features', 'route' => 'website.features'],
                    ['label' => 'Pricing', 'route' => 'website.pricing'],
                ],
            ],
            [
                'title' => 'Company',
                'links' => [
                    ['label' => 'About', 'route' => 'website.about'],
                    ['label' => 'Team', 'route' => 'website.team'],
                    ['label' => 'Customers', 'route' => 'website.customers'],
                    ['label' => 'FAQ', 'route' => 'website.faq'],
                    ['label' => 'Book a demo', 'href' => '#contact'],
                    ['label' => 'Sign in', 'route' => 'login'],
                ],
            ],
            [
                'title' => 'Resources',
                'links' => [
                    ['label' => 'Blog', 'href' => '#'],
                    ['label' => 'Playbooks', 'href' => '#'],
                    ['label' => 'Help centre', 'href' => '#'],
                    ['label' => 'Status', 'href' => '#'],
                    ['label' => 'Changelog', 'href' => '#'],
                ],
            ],
            [
                'title' => 'Legal',
                'links' => [
                    ['label' => 'Privacy', 'href' => '#'],
                    ['label' => 'Terms', 'href' => '#'],
                    ['label' => 'Data processing', 'href' => '#'],
                    ['label' => 'Security', 'href' => '#'],
                    ['label' => 'Cookies', 'href' => '#'],
                ],
            ],
        ],
    ],
];
