<?php

return [
    'roles' => [
        'admin' => 'Administrator',
        'finance' => 'Finance',
        'manager' => 'Manager',
        'rep' => 'Sales Representative',
    ],
    'permission_levels' => [
        'view' => 'View',
        'edit' => 'Edit',
        'admin' => 'Admin',
    ],
    'owner_roles' => ['admin', 'manager', 'rep'],
    'modules' => [
        'dashboard' => [
            'label' => 'Dashboard',
            'caption' => 'CRM overview',
            'icon' => 'bx bxs-grid-alt',
            'route' => 'crm.dashboard',
            'match' => ['crm.dashboard'],
            'default_permissions' => [
                'admin' => 'admin',
                'finance' => 'view',
                'manager' => 'view',
                'rep' => 'view',
            ],
        ],
        'customers' => [
            'label' => 'Customers',
            'caption' => 'Leads and clients',
            'icon' => 'bx bxs-school',
            'route' => 'crm.leads.index',
            'match' => ['crm.leads.*', 'crm.customers.*'],
            'default_permissions' => [
                'admin' => 'admin',
                'manager' => 'edit',
                'rep' => 'edit',
            ],
            'children' => [
                [
                    'label' => 'Leads',
                    'route' => 'crm.leads.index',
                    'match' => ['crm.leads.*'],
                ],
                [
                    'label' => 'Customers',
                    'route' => 'crm.customers.index',
                    'match' => ['crm.customers.*'],
                ],
            ],
        ],
        'contacts' => [
            'label' => 'Contacts',
            'caption' => 'Decision makers',
            'icon' => 'bx bx-user-pin',
            'route' => 'crm.contacts.index',
            'match' => ['crm.contacts.*'],
            'default_permissions' => [
                'admin' => 'admin',
                'manager' => 'edit',
                'rep' => 'edit',
            ],
        ],
        'calendar' => [
            'label' => 'Calendar',
            'caption' => 'Meetings and follow-ups',
            'icon' => 'bx bx-calendar',
            'route' => 'crm.calendar.index',
            'match' => ['crm.calendar.*'],
            'default_permissions' => [
                'admin' => 'admin',
                'finance' => 'edit',
                'manager' => 'edit',
                'rep' => 'edit',
            ],
        ],
        'products' => [
            'label' => 'Products',
            'caption' => 'Catalog, quotes, and invoices',
            'icon' => 'bx bx-package',
            'route' => 'crm.products.catalog.index',
            'match' => ['crm.products.*', 'crm.settings.commercial*'],
            'default_permissions' => [
                'admin' => 'admin',
                'finance' => 'admin',
                'manager' => 'edit',
                'rep' => 'edit',
            ],
            'children' => [
                [
                    'label' => 'Catalog',
                    'route' => 'crm.products.catalog.index',
                    'match' => ['crm.products.catalog.*'],
                    'roles' => ['admin', 'finance', 'manager', 'rep'],
                ],
                [
                    'label' => 'Quotes',
                    'route' => 'crm.products.quotes.index',
                    'match' => ['crm.products.quotes.*'],
                    'roles' => ['admin', 'finance', 'manager', 'rep'],
                ],
                [
                    'label' => 'Invoices',
                    'route' => 'crm.products.invoices.index',
                    'match' => ['crm.products.invoices.*'],
                    'roles' => ['admin', 'finance', 'manager', 'rep'],
                ],
                [
                    'label' => 'Settings',
                    'route' => 'crm.products.settings',
                    'match' => ['crm.products.settings*', 'crm.settings.commercial*'],
                    'minimum_permission' => 'admin',
                ],
            ],
            'route_permissions' => [
                [
                    'match' => [
                        'crm.products.settings*',
                        'crm.settings.commercial*',
                        'crm.products.catalog.create',
                        'crm.products.catalog.store',
                        'crm.products.catalog.edit',
                        'crm.products.catalog.update',
                        'crm.products.catalog.status',
                        'crm.products.invoices.create',
                        'crm.products.invoices.store',
                        'crm.products.invoices.edit',
                        'crm.products.invoices.update',
                        'crm.products.invoices.status',
                        'crm.products.invoices.share.*',
                    ],
                    'level' => 'admin',
                ],
            ],
        ],
        'requests' => [
            'label' => 'Requests',
            'caption' => 'Sales and support',
            'icon' => 'bx bx-headphone',
            'route' => 'crm.requests.sales.index',
            'match' => ['crm.requests.*'],
            'default_permissions' => [
                'admin' => 'admin',
                'manager' => 'edit',
                'rep' => 'edit',
            ],
            'children' => [
                [
                    'label' => 'Sales Calls',
                    'route' => 'crm.requests.sales.index',
                    'match' => ['crm.requests.sales.*'],
                ],
                [
                    'label' => 'Support Requests',
                    'route' => 'crm.requests.support.index',
                    'match' => ['crm.requests.support.*'],
                ],
            ],
        ],
        'dev' => [
            'label' => 'Dev',
            'caption' => 'Requested improvements',
            'icon' => 'bx bx-code-block',
            'route' => 'crm.dev.index',
            'match' => ['crm.dev.*'],
            'default_permissions' => [
                'admin' => 'admin',
                'manager' => 'edit',
                'rep' => 'edit',
            ],
        ],
        'discussions' => [
            'label' => 'Discussions',
            'caption' => 'Internal communication',
            'icon' => 'bx bx-chat',
            'route' => 'crm.discussions.index',
            'match' => ['crm.discussions.*'],
            'default_permissions' => [
                'admin' => 'admin',
                'manager' => 'edit',
                'rep' => 'edit',
            ],
            'children' => [
                [
                    'key' => 'hub',
                    'label' => 'Discussions Hub',
                    'route' => 'crm.discussions.index',
                    'match' => ['crm.discussions.index'],
                ],
                [
                    'key' => 'app',
                    'label' => 'App Messaging',
                    'route' => 'crm.discussions.app.workspace',
                    'match' => ['crm.discussions.app.*'],
                ],
                [
                    'key' => 'email',
                    'label' => 'Email',
                    'route' => 'crm.discussions.email.index',
                    'match' => ['crm.discussions.email.*'],
                ],
                [
                    'key' => 'whatsapp',
                    'label' => 'WhatsApp',
                    'route' => 'crm.discussions.whatsapp.index',
                    'match' => ['crm.discussions.whatsapp.*'],
                ],
            ],
        ],
        'leave' => [
            'label' => 'Leave',
            'caption' => 'Leave requests and approvals',
            'icon' => 'bx bx-calendar-check',
            'route' => 'crm.leave.index',
            'match' => ['crm.leave.*'],
            'default_permissions' => [
                'admin' => 'admin',
                'finance' => 'view',
                'manager' => 'edit',
                'rep' => 'edit',
            ],
            'children' => [
                [
                    'label' => 'My Leave',
                    'route' => 'crm.leave.index',
                    'match' => ['crm.leave.index', 'crm.leave.apply', 'crm.leave.store', 'crm.leave.show', 'crm.leave.history', 'crm.leave.balances'],
                ],
                [
                    'label' => 'Approvals',
                    'route' => 'crm.leave.approvals',
                    'match' => ['crm.leave.approvals', 'crm.leave.approvals.review'],
                    'minimum_permission' => 'edit',
                ],
                [
                    'label' => 'Team Calendar',
                    'route' => 'crm.leave.team-calendar',
                    'match' => ['crm.leave.team-calendar', 'crm.leave.team-balances', 'crm.leave.reports'],
                    'minimum_permission' => 'edit',
                ],
                [
                    'label' => 'Settings',
                    'route' => 'crm.leave.types.index',
                    'match' => ['crm.leave.types.*', 'crm.leave.settings', 'crm.leave.settings.update', 'crm.leave.balance-management', 'crm.leave.balance-management.adjust'],
                    'minimum_permission' => 'admin',
                ],
            ],
            'route_permissions' => [
                [
                    'match' => [
                        'crm.leave.index',
                        'crm.leave.show',
                        'crm.leave.history',
                        'crm.leave.balances',
                        'crm.leave.calculate-days',
                    ],
                    'level' => 'view',
                ],
                [
                    'match' => [
                        'crm.leave.apply',
                        'crm.leave.store',
                        'crm.leave.cancel',
                        'crm.leave.approvals',
                        'crm.leave.approvals.review',
                        'crm.leave.team-calendar',
                        'crm.leave.team-balances',
                    ],
                    'level' => 'edit',
                ],
                [
                    'match' => [
                        'crm.leave.types.*',
                        'crm.leave.settings',
                        'crm.leave.settings.update',
                        'crm.leave.balance-management',
                        'crm.leave.balance-management.adjust',
                        'crm.leave.reports',
                    ],
                    'level' => 'admin',
                ],
            ],
        ],
        'attendance' => [
            'label' => 'Attendance',
            'caption' => 'Clock-in and schedules',
            'icon' => 'bx bx-fingerprint',
            'route' => 'crm.attendance.grid',
            'match' => ['crm.attendance.*', 'crm.settings.attendance.*'],
            'default_permissions' => [
                'admin' => 'admin',
                'finance' => 'view',
                'manager' => 'edit',
                'rep' => 'view',
            ],
            'children' => [
                [
                    'label' => 'Team Grid',
                    'route' => 'crm.attendance.grid',
                    'match' => ['crm.attendance.grid*', 'crm.attendance.reports*'],
                ],
                [
                    'label' => 'Settings',
                    'route' => 'crm.settings.attendance.index',
                    'match' => ['crm.settings.attendance.*'],
                    'minimum_permission' => 'admin',
                ],
            ],
            'route_permissions' => [
                [
                    'match' => [
                        'crm.attendance.clock',
                        'crm.attendance.clock-status',
                        'crm.attendance.records.correction',
                    ],
                    'level' => 'view',
                ],
                [
                    'match' => [
                        'crm.attendance.grid',
                        'crm.attendance.records.show',
                        'crm.attendance.records.update',
                        'crm.attendance.corrections.review',
                        'crm.attendance.corrections.pending',
                        'crm.attendance.reports*',
                    ],
                    'level' => 'edit',
                ],
                [
                    'match' => [
                        'crm.settings.attendance.*',
                    ],
                    'level' => 'admin',
                ],
            ],
        ],
        'integrations' => [
            'label' => 'Integrations',
            'caption' => 'School API links',
            'icon' => 'bx bx-plug',
            'route' => 'crm.integrations.index',
            'match' => ['crm.integrations.*'],
            'default_permissions' => [
                'admin' => 'admin',
                'manager' => 'view',
                'rep' => 'view',
            ],
        ],
        'users' => [
            'label' => 'Users',
            'caption' => 'Internal access',
            'icon' => 'bx bx-group',
            'route' => 'crm.users.index',
            'match' => ['crm.users.*'],
            'default_permissions' => [
                'admin' => 'admin',
            ],
            'children' => [
                [
                    'label' => 'Directory',
                    'route' => 'crm.users.index',
                    'match' => ['crm.users.index', 'crm.users.create', 'crm.users.store', 'crm.users.edit', 'crm.users.update'],
                    'minimum_permission' => 'view',
                ],
                [
                    'label' => 'Settings',
                    'route' => 'crm.users.settings.index',
                    'match' => ['crm.users.settings.*'],
                    'minimum_permission' => 'admin',
                ],
            ],
            'route_permissions' => [
                [
                    'match' => ['crm.users.index', 'crm.users.edit'],
                    'level' => 'view',
                ],
                [
                    'match' => [
                        'crm.users.qualifications.attachments.open',
                        'crm.users.qualifications.attachments.download',
                        'crm.users.signatures.open',
                        'crm.users.signatures.download',
                    ],
                    'level' => 'view',
                ],
                [
                    'match' => [
                        'crm.users.create',
                        'crm.users.store',
                        'crm.users.update',
                        'crm.users.qualifications.*',
                        'crm.users.signatures.*',
                        'crm.users.profile.*',
                    ],
                    'level' => 'edit',
                ],
                [
                    'match' => [
                        'crm.users.destroy',
                        'crm.users.roles.*',
                        'crm.users.settings.*',
                    ],
                    'level' => 'admin',
                ],
            ],
        ],
        'settings' => [
            'label' => 'Settings',
            'caption' => 'Pipeline rules',
            'icon' => 'bx bx-cog',
            'route' => 'crm.settings.index',
            'match' => ['crm.settings.*'],
            'default_permissions' => [
                'admin' => 'admin',
            ],
            'children' => [
                [
                    'label' => 'Overview',
                    'route' => 'crm.settings.index',
                    'match' => ['crm.settings.index'],
                    'minimum_permission' => 'admin',
                ],
                [
                    'label' => 'Sales stages',
                    'route' => 'crm.settings.sales-stages',
                    'match' => ['crm.settings.sales-stages*'],
                    'minimum_permission' => 'admin',
                ],
                [
                    'label' => 'Imports',
                    'route' => 'crm.settings.imports',
                    'match' => ['crm.settings.imports*'],
                    'minimum_permission' => 'admin',
                ],
            ],
            'route_permissions' => [
                [
                    'match' => [
                        'crm.settings.sales-stages*',
                        'crm.settings.imports*',
                    ],
                    'level' => 'admin',
                ],
                [
                    'match' => [
                        'crm.settings.index',
                    ],
                    'level' => 'view',
                ],
            ],
        ],
    ],
    'search' => [
        'limit_per_group' => 5,
        'min_query_length' => 2,
    ],
    'presence' => [
        'online_window_minutes' => 3,
        'launcher_poll_seconds' => 10,
        'launcher_limit' => 8,
    ],
    'user_genders' => [
        'female' => 'Female',
        'male' => 'Male',
    ],
    'user_employment_statuses' => [
        'active' => 'Active',
        'probation' => 'Probation',
        'on_leave' => 'On leave',
        'suspended' => 'Suspended',
        'terminated' => 'Terminated',
    ],
    'user_login_event_types' => [
        'login' => 'Login',
        'logout' => 'Logout',
        'quick_access_login' => 'Quick access login',
    ],
    'lead_statuses' => [
        'active' => 'Active',
        'qualified' => 'Qualified',
        'converted' => 'Converted',
        'lost' => 'Lost',
    ],
    'customer_statuses' => [
        'active' => 'Active',
        'onboarding' => 'Onboarding',
        'inactive' => 'Inactive',
    ],
    'request_types' => [
        'sales' => 'Sales',
        'support' => 'Support',
    ],
    'support_statuses' => [
        'open' => 'Open',
        'in_progress' => 'In Progress',
        'resolved' => 'Resolved',
        'closed' => 'Closed',
    ],
    'request_outcomes' => [
        'pending' => 'Pending',
        'won' => 'Won',
        'lost' => 'Lost',
    ],
    'activity_types' => [
        'call' => 'Call',
        'email' => 'Email',
        'meeting' => 'Meeting',
        'note' => 'Note',
    ],
    'calendar_types' => [
        'personal' => 'Personal',
        'shared' => 'Shared',
    ],
    'calendar_member_permissions' => [
        'view' => 'View',
        'edit' => 'Edit',
        'manage' => 'Manage',
    ],
    'calendar_event_statuses' => [
        'scheduled' => 'Scheduled',
        'completed' => 'Completed',
        'cancelled' => 'Cancelled',
    ],
    'calendar_event_visibility' => [
        'standard' => 'Visible',
        'busy_only' => 'Busy only',
        'private' => 'Private',
    ],
    'calendar_attendee_response_statuses' => [
        'available' => 'Available',
        'tentative' => 'Tentative',
        'unavailable' => 'Unavailable',
    ],
    'calendar_reminder_minutes' => [
        5 => '5 minutes before',
        15 => '15 minutes before',
        30 => '30 minutes before',
        60 => '1 hour before',
        120 => '2 hours before',
        1440 => '1 day before',
    ],
    'calendar_default_colors' => [
        '#5156be',
        '#f06548',
        '#0ab39c',
        '#299cdb',
        '#f7b84b',
        '#405189',
        '#6559cc',
        '#0d6efd',
    ],
    'calendar' => [
        'default_event_duration_minutes' => 60,
        'slot_duration_minutes' => 30,
        'day_start_hour' => '07:00:00',
        'day_end_hour' => '21:00:00',
        'agenda_days' => 14,
    ],
    'commercial_discount_types' => [
        'none' => 'None',
        'fixed' => 'Fixed amount',
        'percent' => 'Percentage',
    ],
    'commercial_product_types' => [
        'license' => 'License',
        'addon' => 'Add-on',
        'implementation' => 'Implementation',
        'support' => 'Support',
        'training' => 'Training',
        'service' => 'Service',
    ],
    'commercial_billing_frequencies' => [
        'one_time' => 'One-time',
        'monthly' => 'Monthly',
        'quarterly' => 'Quarterly',
        'annual' => 'Annual',
        'custom' => 'Custom',
    ],
    'quote_statuses' => [
        'draft' => 'Draft',
        'sent' => 'Sent',
        'accepted' => 'Accepted',
        'rejected' => 'Rejected',
        'expired' => 'Expired',
        'cancelled' => 'Cancelled',
    ],
    'invoice_statuses' => [
        'draft' => 'Draft',
        'issued' => 'Issued',
        'sent' => 'Sent',
        'cancelled' => 'Cancelled',
        'void' => 'Void',
    ],
    'development_statuses' => [
        'backlog' => 'Backlog',
        'planned' => 'Planned',
        'in_progress' => 'In Progress',
        'shipped' => 'Shipped',
        'declined' => 'Declined',
    ],
    'development_priorities' => [
        'low' => 'Low',
        'medium' => 'Medium',
        'high' => 'High',
        'critical' => 'Critical',
    ],
    'discussion_channels' => [
        'app' => 'In-app message',
        'email' => 'Email',
        'whatsapp' => 'WhatsApp',
    ],
    'discussion_delivery_statuses' => [
        'sent' => 'Sent',
        'queued' => 'Queued',
        'pending_integration' => 'Pending integration',
        'failed' => 'Failed',
    ],
    'integration_kinds' => [
        'school_api' => 'School API',
        'email' => 'Email provider',
        'whatsapp' => 'WhatsApp provider',
        'webhook' => 'Webhook',
    ],
    'integration_statuses' => [
        'active' => 'Active',
        'inactive' => 'Inactive',
        'testing' => 'Testing',
    ],
    'import_statuses' => [
        'draft' => 'Draft',
        'validated' => 'Validated',
        'queued' => 'Queued',
        'processing' => 'Processing',
        'completed' => 'Completed',
        'completed_with_errors' => 'Completed With Errors',
        'failed' => 'Failed',
        'cancelled' => 'Cancelled',
    ],
    'imports' => [
        'queue' => [
            'connection' => env('CRM_IMPORT_QUEUE_CONNECTION', env('QUEUE_CONNECTION', 'database')),
            'queue' => env('CRM_IMPORT_QUEUE_NAME', 'crm-imports'),
        ],
        'entities' => [
            'users' => [
                'label' => 'Users',
                'description' => 'Import internal CRM users with profile, employment, and reusable filter details.',
                'template_filename' => 'crm-users-import-template.xlsx',
                'headings' => [
                    'name',
                    'email',
                    'role',
                    'active',
                    'date_of_birth',
                    'gender',
                    'nationality',
                    'id_number',
                    'phone',
                    'employment_status',
                    'department',
                    'position',
                    'reports_to_email',
                    'personal_payroll_number',
                    'date_of_appointment',
                    'custom_filters',
                ],
                'required' => ['name', 'email', 'role'],
                'match_key' => 'email',
            ],
            'leads' => [
                'label' => 'Leads',
                'description' => 'Import institutional leads using a stable external reference for repeat upserts.',
                'template_filename' => 'crm-leads-import-template.xlsx',
                'headings' => ['import_reference', 'owner_email', 'company_name', 'industry', 'website', 'email', 'phone', 'fax', 'country', 'region', 'location', 'postal_address', 'status', 'notes'],
                'required' => ['import_reference', 'company_name'],
                'match_key' => 'import_reference',
            ],
            'customers' => [
                'label' => 'Customers',
                'description' => 'Import customer accounts by institution name and create a linked converted source lead when needed.',
                'template_filename' => 'crm-customers-import-template.xlsx',
                'headings' => ['owner_email', 'company_name', 'industry', 'website', 'email', 'phone', 'fax', 'country', 'region', 'location', 'postal_address', 'status', 'purchased_at', 'notes'],
                'required' => ['company_name'],
                'match_key' => 'company_name',
            ],
            'contacts' => [
                'label' => 'Contacts',
                'description' => 'Import decision-makers linked to an existing lead reference.',
                'template_filename' => 'crm-contacts-import-template.xlsx',
                'headings' => ['import_reference', 'lead_import_reference', 'name', 'job_title', 'email', 'phone', 'is_primary', 'owner_email', 'notes'],
                'required' => ['import_reference', 'lead_import_reference', 'name'],
                'match_key' => 'import_reference',
            ],
        ],
    ],
    'leave' => [
        'attendance_integration' => [
            'enabled' => false,
            'leave_attendance_code' => 'L',
            'half_day_attendance_code' => 'HD',
            'source_identifier' => 'leave_system',
        ],
    ],
    'attendance' => [
        'queue' => [
            'connection' => env('CRM_ATTENDANCE_QUEUE_CONNECTION', env('QUEUE_CONNECTION', 'database')),
            'queue' => env('CRM_ATTENDANCE_QUEUE_NAME', 'crm-attendance'),
        ],
        'auto_close_time' => '23:59:59',
        'mark_absent_at' => '17:30',
        'clock_debounce_seconds' => 60,
        'max_daily_hours' => 24,
        'biometric_heartbeat_timeout_minutes' => 30,
        'device_brands' => [
            'zkteco' => [
                'label' => 'ZKTeco',
                'protocol' => 'adms',
                'default_port' => 80,
                'models' => [
                    'SpeedFace-V5L' => 'SpeedFace-V5L (Face + Palm)',
                    'ProFace-X' => 'ProFace X (Face + Fingerprint + Palm)',
                    'iClock-880-H' => 'iClock 880-H (Fingerprint + Face)',
                    'MB460' => 'MB460 (Multi-biometric)',
                    'UFace-800' => 'UFace 800 (Face)',
                    'K40-Pro' => 'K40 Pro (Fingerprint)',
                    'ZK-SF300' => 'SF300 (Fingerprint)',
                    'other' => 'Other ZKTeco model',
                ],
            ],
            'hikvision' => [
                'label' => 'Hikvision',
                'protocol' => 'isapi',
                'default_port' => 80,
                'models' => [
                    'DS-K1T341AMF' => 'DS-K1T341AMF (Face + Fingerprint)',
                    'DS-K1T671TM' => 'DS-K1T671TM (Face + Card)',
                    'DS-K1A802' => 'DS-K1A802 Series (Fingerprint)',
                    'MinMoe' => 'MinMoe Series (Face + Card)',
                    'other' => 'Other Hikvision model',
                ],
            ],
            'suprema' => [
                'label' => 'Suprema',
                'protocol' => 'biostar',
                'default_port' => 443,
                'models' => [
                    'BioStation-3' => 'BioStation 3 (Face + Fingerprint)',
                    'FaceStation-F2' => 'FaceStation F2 (Face)',
                    'BioStation-A2' => 'BioStation A2 (Fingerprint + Card)',
                    'BioEntry-W2' => 'BioEntry W2 (Fingerprint + Card)',
                    'other' => 'Other Suprema model',
                ],
            ],
            'anviz' => [
                'label' => 'Anviz',
                'protocol' => 'crosschex',
                'default_port' => 5010,
                'models' => [
                    'FaceDeep-5' => 'FaceDeep 5 (Face)',
                    'W2-Pro' => 'W2 Pro (Fingerprint + Card)',
                    'EP300-Pro' => 'EP300 Pro (Fingerprint)',
                    'C2-Pro' => 'C2 Pro (Fingerprint)',
                    'other' => 'Other Anviz model',
                ],
            ],
            'generic' => [
                'label' => 'Generic / Other',
                'protocol' => 'push',
                'default_port' => 80,
                'models' => [
                    'other' => 'Custom / Third-party device',
                ],
            ],
        ],
        'verify_methods' => [
            'fingerprint' => 'Fingerprint',
            'face' => 'Face Recognition',
            'card' => 'RFID Card',
            'pin' => 'PIN / Password',
            'palm' => 'Palm Print',
            'palm_vein' => 'Palm Vein',
            'finger_vein' => 'Finger Vein',
            'iris' => 'Iris',
            'qr_code' => 'QR Code',
            'bluetooth' => 'Bluetooth / Mobile',
            'card_fingerprint' => 'Card + Fingerprint',
            'card_pin' => 'Card + PIN',
            'face_fingerprint' => 'Face + Fingerprint',
        ],
        'zkteco_verify_codes' => [
            0 => 'pin',
            1 => 'fingerprint',
            2 => 'card',
            3 => 'card_pin',
            4 => 'card_fingerprint',
            9 => 'card_pin',
            15 => 'face',
            20 => 'palm',
            21 => 'finger_vein',
        ],
        'zkteco_punch_states' => [
            0 => 'clock_in',
            1 => 'clock_out',
            2 => 'break_out',
            3 => 'break_in',
            4 => 'overtime_in',
            5 => 'overtime_out',
        ],
        'device_protocols' => [
            'adms' => 'ZKTeco ADMS (Push)',
            'isapi' => 'Hikvision ISAPI (Push)',
            'biostar' => 'Suprema BioStar API',
            'crosschex' => 'Anviz CrossChex',
            'push' => 'Generic Push (JSON)',
        ],
        'device_directions' => [
            'both' => 'Both (In & Out)',
            'in' => 'Entry only',
            'out' => 'Exit only',
        ],
    ],
];
